- set_fact:
    whalebrew: {}

- name: check whalebrew
  stat:
    path: '{{ whalebrew.bin_path }}'
  register: whalebrew_stat
  when: whalebrew.bin_path

- name: install binary
  get_url:
    url: 'https://github.com/bfirsh/whalebrew/releases/download/{{ whalebrew.version }}/whalebrew-{{ ansible_system }}-{{ ansible_machine }}'
    dest: '{{ whalebrew.bin_path }}'
    mode: 0755
  when: whalebrew.version and not (whalebrew_stat.get('stat') and whalebrew_stat.stat.exists)

# - name: install packages
#   command: |
#     bash -lc 'whalebrew install {{ item }}'
#   with_items: '{{ whalebrew.packages }}'
#   when: whalebrew.packages
