# https://alacritty.org/config-alacritty.html

[colors.primary]
background = "0x1b1b1b" # candle-theme: background
foreground = "0xc0c0c0" # candle-theme: foreground

[colors.normal]
black   = "0x424242" # candle-theme: gray400
blue    = "0x8ca2b6" # candle-theme: blue
cyan    = "0x9abbb6" # candle-theme: aqua
green   = "0xa6b083" # candle-theme: green
magenta = "0xa186a3" # candle-theme: purple
red     = "0xa57572" # candle-theme: red
white   = "0x575757" # candle-theme: gray300
yellow  = "0xd0b888" # candle-theme: yellow

[colors.bright]
black   = "0x424242" # candle-theme: gray400
blue    = "0x82a4c3" # candle-theme: bright_red
cyan    = "0x80c7bc" # candle-theme: bright_green
green   = "0xa5b56b" # candle-theme: bright_yellow
magenta = "0xb07bb4" # candle-theme: bright_blue
red     = "0xb56e6a" # candle-theme: bright_purple
white   = "0x575757" # candle-theme: bright_aqua
yellow  = "0xd8b775" # candle-theme: gray300

[colors.dim]
black   = "0x424242" # candle-theme: gray400
blue    = "0x39444d" # candle-theme: dark_red
cyan    = "0x3c4e4b" # candle-theme: dark_green
green   = "0x4c4b30" # candle-theme: dark_yellow
magenta = "0x47404d" # candle-theme: dark_blue
red     = "0x503131" # candle-theme: dark_purple
white   = "0x575757" # candle-theme: dark_aqua
yellow  = "0x5f5138" # candle-theme: gray300

[font]
size = 12.0

[font.glyph_offset]
x = 0
y = 1

[font.offset]
x = 0
y = 2

[[keyboard.bindings]] # @see https://github.com/jwilm/alacritty/issues/1359
chars = "\u0011"
key = "Q"
mods = "Control"

[mouse]
hide_when_typing = false # @see https://github.com/alacritty/alacritty/issues/6452

[shell]
args = ["-l", "-u"] # @see https://github.com/tmux/tmux/issues/328
program = "/opt/homebrew/bin/tmux"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Maximized"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 6
y = 6
