link_mappings:
  aws/config:                             .aws/config
  bash/bash_profile:                      .bash_profile
  bash/bashrc:                            .bashrc
  config/agignore:                        .agignore
  config/ansible.cfg:                     .ansible.cfg
  config/coffeelintrc:                    .coffeelintrc
  config/ctags:                           .ctags
  config/curlrc:                          .curlrc
  config/lldbinit:                        .lldbinit
  config/pgclirc:                         .pgclirc
  config/ranger/colorschemes/original.py: .config/ranger/colorschemes/original.py
  config/ranger/rc.conf:                  .config/ranger/rc.conf
  dotssh:                                 .dotssh
  git/gitconfig:                          .gitconfig
  git/gitignore:                          .gitignore
  peco:                                   .peco
  ruby/gemrc:                             .gemrc
  ruby/irbrc:                             .irbrc
  ruby/pryrc:                             .pryrc
  ruby/railsrc:                           .railsrc
  ruby/rbenv/default-gems:                .anyenv/envs/rbenv/default-gems
  ruby/rspec:                             .rspec
  ruby/bundle/config:                     .bundle/config
  tmux/tmux.conf:                         .tmux.conf
  tmux:                                   .tmux
  vim/gvimrc:                             .gvimrc
  vim/vimrc:                              .vimrc
  vim:                                    .vim
  zsh/zshenv:                             .zshenv
  zsh/zshrc:                              .zshrc
  zsh:                                    .zsh
