- ansible.builtin.set_fact:
    vagrant: {}

- name: install applications
  community.general.homebrew_cask:
    name:
      - vagrant    # https://www.vagrantup.com/
      #- virtualbox # https://www.virtualbox.org/
    state: latest
    accept_external_apps: true
    sudo_password: '{{ ansible_become_pass }}'

- name: get installed boxes
  ansible.builtin.command: |
    bash -lc 'vagrant box list'
  register: installed_boxes

- name: install box
  ansible.builtin.command: |
    bash -lc 'vagrant box add {{ item.key }} {{ item.value }}'
  when: |
    vagrant.boxes is defined and installed_boxes.stdout.find(item.key) == -1
  loop: '{{ vagrant.boxes | dict2items }}'

- name: get installed plugins
  ansible.builtin.command: |
    bash -lc 'vagrant plugin list'
  register: installed_plugins

- name: install plugin
  ansible.builtin.command: |
    bash -lc 'vagrant plugin install {{ item }}'
  when: |
    installed_plugins.stdout.find(item) == -1
  loop:
    - dotenv        # https://github.com/johnbellone/vagrant-dotenv ?
    - sahara        # https://github.com/jedi4ever/sahara
    - vagrant-share # https://www.vagrantup.com/docs/share/
