- set_fact:
    vagrant: {}

- name: install applications
  homebrew_cask:
    name:
      - vagrant    # https://www.vagrantup.com/
      #- virtualbox # https://www.virtualbox.org/
    state: present
    accept_external_apps: yes

- name: get installed boxes
  command: |
    /usr/local/bin/vagrant box list
  register: installed_boxes

- name: install box
  command: |
    /usr/local/bin/vagrant box add {{ item.key | quote }} {{ item.value | quote }}
  when: |
    vagrant.boxes and installed_boxes.stdout.find(item.key) == -1
  with_dict: '{{ vagrant.boxes }}'

- name: get installed plugins
  command: |
    /usr/local/bin/vagrant plugin list
  register: installed_plugins

- name: install plugin
  command: |
    /usr/local/bin/vagrant plugin install {{ item | quote }}
  when: |
    vagrant.plugins and installed_plugins.stdout.find(item) == -1
  with_items: '{{ vagrant.plugins }}'
