#=== General
#==============================================================================================
- name: general | set sidebar icon size to small
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSTableViewDefaultSizeMode
    type:   int
    value:  1

- name: general | increase window resize speed
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSWindowResizeTime
    type:   float
    value:  0.001

- name: general | expand filer panel by default (1/2)
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSNavPanelExpandedStateForSaveMode
    type:   bool
    value:  true

- name: general | expand filer panel by default (2/2)
  osx_defaults:
    domain: NSGlobalDomain
    key:    PMPrintingExpandedStateForPrint
    type:   bool
    value:  true

- name: general | automatically quit the printer app after complete
  osx_defaults:
    domain: com.apple.print.PrintingPrefs
    key:    'Quit When Finished'
    type:   bool
    value:  true

- name: general | disable the "Are you sure you want to open this application?" dialog
  osx_defaults:
    domain: com.apple.LaunchServices
    key:    LSQuarantine
    type:   bool
    value:  false

- name: general | disable the crash reporter
  osx_defaults:
    domain: com.apple.CrashReporter
    key:    DialogType
    type:   string
    value:  none

- name: general | disable smart quotes
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSAutomaticQuoteSubstitutionEnabled
    type:   bool
    value:  false

- name: general | disable smart dashes
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSAutomaticDashSubstitutionEnabled
    type:   bool
    value:  false

- name: general | keyboard & trackpad (1/4)
  osx_defaults:
    domain: NSGlobalDomain
    key:    com.apple.keyboard.fnState
    type:   bool
    value:  false

- name: general | keyboard & trackpad (2/4)
  osx_defaults:
    domain: NSGlobalDomain
    key:    com.apple.trackpad.scaling
    type:   float
    value:  3.0

- name: general | keyboard & trackpad (3/4)
  osx_defaults:
    domain: NSGlobalDomain
    key:    com.apple.springing.delay
    type:   float
    value:  0.5

- name: general | keyboard & trackpad (4/4)
  osx_defaults:
    domain: NSGlobalDomain
    key:    com.apple.springing.enabled
    type:   bool
    value:  true

- name: general | touch bar
  osx_defaults:
    domain: com.apple.touchbar.agent
    key:    PresentationModeGlobal
    type:   string
    value:  fullControlStrip

- name: general | skin (1/6)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleAntiAliasingThreshold
    type:   int
    value:  4

- name: general | skin (2/6)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleAquaColorVariant
    type:   int
    value:  6

- name: general | skin (3/6)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleEnableMenuBarTransparency
    type:   bool
    value:  true

- name: general | skin (4/6)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleEnableSwipeNavigateWithScrolls
    type:   bool
    value:  false

- name: general | skin (5/6)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleInterfaceStyle
    type:   string
    value:  Dark

- name: general | skin (6/6)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleKeyboardUIMode
    type:   int
    value:  2

#=== Input device
#==============================================================================================
- name: input device | key repeat
  osx_defaults:
    domain: NSGlobalDomain
    key:    KeyRepeat
    type:   int
    value:  1 # 1Hz = 16.7ms

- name: input device | delay until repeat
  osx_defaults:
    domain: NSGlobalDomain
    key:    InitialKeyRepeat
    type:   int
    value:  12 # 12Hz = 200ms

- name: input device | disable accents popup
  osx_defaults:
    domain: NSGlobalDomain
    key:    ApplePressAndHoldEnabled
    type:   bool
    value:  false

- name: input device | enable full keyboard access for all controls
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleKeyboardUIMode
    type:   int
    value:  3

- name: input device | set language and text formats (1/5)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleLanguages
    type:   array
    value:
      - en
      - ja
  when: false  # FIXME

- name: input device | set language and text formats (2/5)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleLocale
    type:   string
    value:  'en_JP@currency=JPY'

- name: input device | set language and text formats (3/5)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleMeasurementUnits
    type:   string
    value:  Centimeters

- name: input device | set language and text formats (4/5)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleMetricUnits
    type:   bool
    value:  true

- name: input device | set language and text formats (5/5)
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleICUForce24HourTime
    type:   bool
    value:  true

- name: input device | disable auto-correct
  osx_defaults:
    domain: NSGlobalDomain
    key:    NSAutomaticSpellingCorrectionEnabled
    type:   bool
    value:  false

#=== Screenshot
#==============================================================================================
- name: screenshot | save to the desktop
  osx_defaults:
    domain: com.apple.screencapture
    key:    location
    type:   string
    value:  '{{ home_path }}/Desktop'

- name: screenshot | save screenshots in png format
  osx_defaults:
    domain: com.apple.screencapture
    key:    type
    type:   string
    value:  png

- name: screenshot | disable shadow
  osx_defaults:
    domain: com.apple.screencapture
    key:    disable-shadow
    type:   bool
    value:  true

#=== Finder
#==============================================================================================
- name: finder | show hidden files by default
  osx_defaults:
    domain: com.apple.finder
    key:    AppleShowAllFiles
    type:   bool
    value:  true

- name: finder | show all filename extensions
  osx_defaults:
    domain: NSGlobalDomain
    key:    AppleShowAllExtensions
    type:   bool
    value:  true

- name: finder | show status bar
  osx_defaults:
    domain: com.apple.finder
    key:    ShowStatusBar
    type:   bool
    value:  true

- name: finder | show path bar
  osx_defaults:
    domain: com.apple.finder
    key:    ShowPathbar
    type:   bool
    value:  true

- name: finder | allow text selection in Quick Look
  osx_defaults:
    domain: com.apple.finder
    key:    QLEnableTextSelection
    type:   bool
    value:  true

- name: finder | search the current folder by default
  osx_defaults:
    domain: com.apple.finder
    key:    FXDefaultSearchScope
    type:   string
    value:  SCcf

- name: finder | disable the warning when changing a file extension
  osx_defaults:
    domain: com.apple.finder
    key:    FXEnableExtensionChangeWarning
    type:   bool
    value:  false

- name: finder | avoid creating .DS_Store files on network volumes
  osx_defaults:
    domain: com.apple.desktopservices
    key:    DSDontWriteNetworkStores
    type:   bool
    value:  true

- name: finder | don't create desktop
  osx_defaults:
    domain: com.apple.finder
    key:    CreateDesktop
    type:   bool
    value:  false

- name: finder | display line numbers and wrap text
  osx_defaults:
    domain: org.n8gray.QLColorCode
    key:    extraHLFlags
    type:   string
    value:  '-l -W'

#=== Dock
#==============================================================================================
- name: dock | set the icon size of Dock items
  osx_defaults:
    domain: com.apple.dock
    key:    tilesize
    type:   float
    value:  16.0

- name: dock | minimize windows into their application's icon
  osx_defaults:
    domain: com.apple.dock
    key:    minimize-to-application
    type:   bool
    value:  true

- name: dock | disable animations (1/4)
  osx_defaults:
    domain: com.apple.dock
    key:    expose-animation-duration
    type:   int
    value:  0

- name: dock | disable animations (2/4)
  osx_defaults:
    domain: com.apple.dock
    key:    workspaces-swoosh-animation-off
    type:   bool
    value:  true

- name: dock | disable animations (3/4)
  osx_defaults:
    domain: com.apple.dock
    key:    springboard-show-duration
    type:   int
    value:  0

- name: dock | disable animations (4/4)
  osx_defaults:
    domain: com.apple.dock
    key:    springboard-hide-duration
    type:   int
    value:  0

- name: dock | disable Dashboard
  osx_defaults:
    domain: com.apple.dashboard
    key:    mcx-disabled
    type:   bool
    value:  true

- name: dock | don't show Dashboard as a Space
  osx_defaults:
    domain: com.apple.dock
    key:    dashboard-in-overlay
    type:   bool
    value:  true

- name: dock | don't automatically rearrange Spaces based on most recent use
  osx_defaults:
    domain: com.apple.dock
    key:    mru-spaces
    type:   bool
    value:  false

- name: dock | automatically hide and show the Dock
  osx_defaults:
    domain: com.apple.dock
    key:    autohide
    type:   bool
    value:  true

- name: dock | make Dock icons of hidden applications translucent
  osx_defaults:
    domain: com.apple.dock
    key:    showhidden
    type:   bool
    value:  true
