- name: reload quicklook
  ansible.builtin.command: |
    qlmanage -r

- name: disable the sound effects on boot
  ansible.builtin.command: |
    nvram StartupMute=%01
  become: true

- name: show the ~/Library folder
  ansible.builtin.command: |
    chflags nohidden ~/Library

- name: restart affected app
  ansible.builtin.command: |
    killall '{{ item }}'
  loop:
    - Dock
    - Finder
