#!/usr/bin/env bash

brew tap phinze/homebrew-cask
brew install brew-cask

function cask() {
	brew cask install "${@}" 2> /dev/null
}

cask dropbox
cask google-chrome
cask google-chrome-canary
cask imagealpha
cask imageoptim
cask iterm2
cask sublime-text
cask the-unarchiver
cask transmission
cask virtualbox


