#!/usr/bin/env bash

cask() {
  brew cask install "${@}" 2> /dev/null
}


cask anvil
cask dropbox
cask firefox
cask flip4mac
cask google-chrome
cask google-chrome-canary
cask handbrake
cask imagealpha
cask imageoptim
cask iterm2
cask keyremap4macbook
cask sequel-pro
cask skype
cask sophos-antivirus
cask sublime-text
cask the-unarchiver
cask transmission
cask truecrypt
cask vagrant
cask virtualbox
cask xtrafinder

