#!/usr/bin/env bash

printf "\e[33m"
echo ""
printf "\e[0m"

exit
if ! [ -d ~/dotfiles/.git ]; then
  echo "Cloning repo..."
  cd ~
  git clone --recursive git@github.com:creasty/dotfiles.git
fi

cd ~/dotfiles

./bootstrap.d/install
./bootstrap.d/link
./bootstrap.d/shell
./bootstrap.d/app
./bootstrap.d/font
./bootstrap.d/osx
