#!/bin/bash

if ! [ -d ~/dotfiles/.git ]; then
  echo "Cloning repo..."
  cd ~
  git clone --recursive git@github.com:creasty/dotfiles.git
fi

cd ~/dotfiles

sh ./script/install
sh ./script/link
sh ./script/shell
sh ./script/app
sh ./script/font
sh ./script/osx
