#!/bin/bash

if ! [ -d ~/dotfiles/.git ]; then
  echo "Cloning repo..."
  cd ~
  git clone --recursive git@github.com:creasty/dotfiles.git
fi

source ~/dotfiles/script/install
source ~/dotfiles/script/link
source ~/dotfiles/script/shell
source ~/dotfiles/script/osx
source ~/dotfiles/script/app
