#!/bin/bash

install() {
  brew install "$@"
}
update() {
  brew update
}
upgrade() {
  brew upgrade
}
tap() {
  brew tap "$@"
}
linkapps() {
  brew linkapps
}
cleanup() {
  brew cleanup
}
cask() {
  brew cask "$@"
}

if [ $# -gt 0 ]; then
  source "$1"
else
  source ./Brewfile
fi
