#!/bin/bash

APP_DIR=~/dotfiles/app


#  Karabiner
#-----------------------------------------------
cp $APP_DIR/karabiner/private.xml ~/Library/Application\ Support/Karabiner/


#  Automator
#-----------------------------------------------
cp $APP_DIR/automator/*.workflow ~/Library/Services/


#  QuickLook
#-----------------------------------------------
cp $APP_DIR/quick_look/*.qlgenerator /Library/QuickLook/

qlmanage -r


#  Launch agent
#-----------------------------------------------
# for f in $APP_DIR/launch_agent/*.plist; do
#   ln -sfv $f ~/Library/LaunchAgents
#   launchctl load "~/Library/LaunchAgents/$(basename $f)"
# done
# unset f
