#!/usr/bin/env bash

cd ~/dotfiles


#  Xcode command line tool
#-----------------------------------------------
xcode-select --install


#  Homebrew
#-----------------------------------------------
which brew > /dev/null 2>&1
if [ $? -ne 0 ]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

sh ./Brewfile


#  rbenv
#-----------------------------------------------
rbenv install 2.1.1
rbenv global 2.1.1


#  Gem
#-----------------------------------------------
rbenv exec gem install bundler
bundle


#  NVM
#-----------------------------------------------
which nvm > /dev/null 2>&1
if [ $? -ne 0 ]; then
  curl https://raw.githubusercontent.com/creationix/nvm/v0.17.3/install.sh | bash
fi
nvm install 0.10


#  Node packages
#-----------------------------------------------
npm i -g


#  Vagrant
#-----------------------------------------------
# vagrant box add centos64-6.5.3 https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box
# vagrant plugin install sahara


#  R
#-----------------------------------------------
r -f packages.r


#  Haskell
#-----------------------------------------------
cabal update
cabal install cabal-install
cabal install erd


#  Lua
#-----------------------------------------------
luarocks install md5
luarocks install stdlib
luarocks install lgi
luarocks install lpeg
luarocks install luaexpat
luarocks install inspect
luarocks install luaepnf
luarocks install luarepl
luarocks install cassowary


#  Python
#-----------------------------------------------
pip install howdoi
