#!/usr/bin/env bash

cd $DOTFILES_PATH
source $DOTFILES_PATH/lib/helpers.sh

INSTALLERS_PATH=$DOTFILES_PATH/bootstrap.d/install.d

INSTALLERS=(
  xcode_cli
  homebrew

  rbenv
  nodejs
  vagrant
  r
  haskell
  lua
  python
  golang

  redis
  rsense
  elasticsearch
)

for installer in "${INSTALLERS[@]}"; do
  (source "$INSTALLERS_PATH/${installer}.sh")
done
