#!/usr/bin/env bash

source $DOTFILES_PATH/lib/helpers.sh

SRC_DIR="$DOTFILES_PATH"
DEST_DIR="$HOME"

LINKS=(
  _agignore
  _ansible.cfg
  _bash/bash_profile:.bash_profile
  _bash/bashrc:.bashrc
  _coffeelintrc
  _config/ranger/colorschemes/original.py
  _config/ranger/rc.conf
  _ctags
  _curlrc
  _dotssh
  _gemrc
  _git/gitconfig:.gitconfig
  _git/gitignore:.gitignore
  _irbrc
  _peco
  _railsrc
  _rbenv/default-gems
  _rspec
  _tmux
  _tmux/tmux.conf:.tmux.conf
  _vim
  _vim/gvimrc:.gvimrc
  _vim/vimrc:.vimrc
  _zsh
  _zsh/zshenv:.zshenv
  _zsh/zshrc:.zshrc
)


section "Creating symbolic links"

for link in "${LINKS[@]}"; do
  src="${link%%:*}"
  dest="${link#*:}"

  if [ "$dest" = "$src" ]; then
    dest="$(echo "$src" | sed 's/^_/./' | tr -d "\n")"
  fi

  src="$SRC_DIR/$src"
  dest="$DEST_DIR/$dest"
  dest_dir="$(dirname $dest)"

  if [ ! -d "$dest_dir" ]; then
    mkdir -p "$dest_dir"
    print_info "Created directory `$dest_dir`"
  fi

  if [ ! -L "$dest" ]; then
    if [ -f "$dest" ]; then
      print_error "File exists at $dest"
    else
      ln -sf "$src" "$dest"
      print_info "Linked: $src --> $dest"
    fi
  fi
done

print_success "OK"
