#!/usr/bin/env bash

if ! [ $ZSH_NAME ]; then
  echo "Change login shell..."

  sudo mv /etc/zshenv /etc/_zshenv
  echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
  chpass -s /usr/local/bin/zsh

  echo "ok"
fi
