#!/usr/bin/env bash

source $DOTFILES_PATH/lib/helpers.sh

section "Change login shell to zsh"

if [ "$SHELL" == "/usr/local/bin/zsh" ]; then
  print_info "Skipped"
else
  [ -f /etc/zshenv ] && sudo mv /etc/zshenv /etc/_zshenv

  if [ "$(cat /etc/shells | grep /usr/local/bin/zsh)" == "" ]; then
    echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells
  fi

  chpass -s /usr/local/bin/zsh

  print_success "Changed"
fi
