- set_fact:
    lua: {}

- name: check luaenv
  command: |
    bash -ic 'which luaenv'
  register: which_luaenv
  ignore_errors: yes

- name: install luaenv
  command: |
    bash -ic 'anyenv install luaenv'
  when: which_luaenv.rc > 0

- name: install plugins
  git:
    repo: 'https://github.com/{{ item }}.git'
    dest: '{{ lua.plugins_dir }}/{{ item }}'
  with_items: '{{ lua.plugins }}'
  when: lua.plugins_dir and lua.plugins

- name: get installed versions
  command: |
    bash -ic 'luaenv versions'
  register: installed_versions

- name: install lua
  command: |
    bash -ic 'luaenv install {{ item | quote }}'
  when: |
    lua.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ lua.versions }}'

- name: set global lua
  command: |
    bash -ic 'luaenv global {{ lua.versions[0] | quote }}'
  when: lua.versions

- name: get installed packages
  command: |
    bash -ic 'luarocks list'
  register: installed_packages

- name: install packages
  command: |
     bash -ic 'luarocks install {{ item | quote }}'
  when: |
    lua.packages and installed_packages.stdout.find(item) == -1
  with_items: '{{ lua.packages }}'
