go_versions:
  - 1.7.1

packages:
  - bitbucket.org/liamstask/goose/cmd/goose
  - github.com/b4b4r07/gomi
  - github.com/codegangsta/gin
  - github.com/golang/lint/golint
  - github.com/govend/govend
  - github.com/laurent22/massren
  - github.com/motemen/ghq
  - github.com/nsf/gocode
  - github.com/peco/peco/cmd/peco
  - github.com/rakyll/boom
  - golang.org/x/tools/cmd/gotype
  - github.com/Masterminds/glide
