- ansible.builtin.set_fact:
    launchagent: {}

- name: create directory
  ansible.builtin.file:
    dest:  '{{ home_path }}/Library/LaunchAgents'
    state: directory

- name: copy launch agents
  ansible.builtin.copy:
    src:  '{{ item }}'
    dest: '{{ home_path }}/Library/LaunchAgents/'
  loop_control:
    label: '{{ item | basename }}'
  loop: '{{ query("fileglob", launchagent.plist_dir ~ "/*.plist") }}'
  when: launchagent.plist_dir is defined

- name: load launch agents
  ansible.builtin.command: |
    launchctl load -F -w "{{ home_path }}/Library/LaunchAgents/{{ item | basename }}"
  register: launchctl_load
  loop_control:
    label: '{{ item | basename }}'
  loop: '{{ query("fileglob", launchagent.plist_dir ~ "/*.plist") }}'
  until: launchctl_load.stderr == "" or launchctl_load.stderr.find("already loaded") != -1
  retries: 1
  delay: 0
  when: launchagent.plist_dir is defined
