#  Base
#-----------------------------------------------
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo  = 'Shougo/vimproc.vim'
build = 'make'


#  Editing
#-----------------------------------------------
[[plugins]] # text objects for indented blocks of lines
repo    = 'kana/vim-textobj-indent'
depends = ['vim-textobj-user']

[[plugins]] # create your own text objects
repo = 'kana/vim-textobj-user'

[[plugins]] # text objects for multiple types of parentheses
repo    = 'osyo-manga/vim-textobj-multiblock'
depends = ['vim-textobj-user']

[[plugins]] # deleting, changing, and adding surroundings
repo = 'vim-scripts/surround.vim'

[[plugins]] # async :make and linting framework for neovim/vim
repo = 'neomake/neomake'

[[plugins]] # extended % matching
repo = 'tmhedberg/matchit'

[[plugins]] # pasting with indentation adjusted to paste destination
repo = 'sickill/vim-pasta'

[[plugins]] # a genius template engine
repo = 'creasty/mold.vim'


#  Completion
#-----------------------------------------------
[[plugins]] # auto close parentheses and repeat by dot
repo    = 'cohama/lexima.vim'
depends = ['smartchr', 'deoplete.nvim', 'neosnippet']

[[plugins]] # dark powered asynchronous completion framework for neovim/vim8
repo    = 'Shougo/deoplete.nvim'
depends = ['nvim-yarp', 'vim-hug-neovim-rpc']

[[plugins]] # yet another remote plugin framework for neovim
repo = 'roxma/nvim-yarp'
if   = "!has('nvim')"

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
if   = "!has('nvim')"

[[plugins]]
repo    = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']

[[plugins]]
repo    = 'Shougo/neco-vim'
depends = ['deoplete.nvim']

# [[plugins]]
# repo    = 'autozimu/LanguageClient-neovim'
# rev     = 'next'
# build   = 'bash install.sh'
# depends = ['deoplete.nvim']


#  Utils
#-----------------------------------------------
[[plugins]] # enable repeating supported plugin maps with dot
repo = 'tpope/vim-repeat'

[[plugins]] # a tree explorer
repo = 'scrooloose/nerdtree'

[[plugins]] # pseudo clipboard register
repo = 'kana/vim-fakeclip'

[[plugins]] # run commands quickly
repo = 'thinca/vim-quickrun'

[[plugins]] # create your own submodes
repo = 'kana/vim-submode'

[[plugins]] # ctags generator
repo = 'szw/vim-tags'


#  Appearance
#-----------------------------------------------
[[plugins]] # toggle, display and navigate marks
repo = 'kshenoy/vim-signature'

[[plugins]] # search status
repo   = 'osyo-manga/vim-anzu'
on_map = ['<Plug>(anzu-']

[[plugins]] # candle theme
repo = 'creasty/candle.vim'


#  Language
#-----------------------------------------------
[[plugins]] # React JSX syntax highlighting and indenting
repo = 'mxw/vim-jsx'
