#  Editing
#-----------------------------------------------
[[plugins]] # define your own operator easily
repo  = 'kana/vim-operator-user'
on_if = 1

[[plugins]] # operator to camelize/decamelize a specified text
repo    = 'tyru/operator-camelize.vim'
depends = ['vim-operator-user']
on_map = [
  '<Plug>(operator-camelize)',
  '<Plug>(operator-decamelize)',
  '<Plug>(operator-camelize-toggle)',
]

[[plugins]] # operator to replace text with register content
repo    = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
on_map  = ['<Plug>(operator-replace)']

[[plugins]] # a simple, easy-to-use Vim alignment plugin
repo   = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']

[[plugins]] # insert several candidates with a single key
repo    = 'vim-scripts/smartchr'
on_func = ['smartchr']

[[plugins]] # switch segments of text with predefined replacements
repo   = 'AndrewRadev/switch.vim'
on_cmd = ['Switch']

[[plugins]] # maniplate selected text easily
repo   = 't9md/vim-textmanip'
on_map = ['<Plug>(textmanip-']

[[plugins]] # sequencial numbering with pattern
repo   = 'deris/vim-rengbang'
on_cmd = ['RengBang']

[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_func = ['emmet']


#  Completion
#-----------------------------------------------
[[plugins]] # syntax source for neocomplete/deoplete/ncm
repo    = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']
on_i    = 1
hook_source = '''
let g:necosyntax#min_keyword_length = 3
'''

[[plugins]] # vim source for neocomplete/deoplete
repo    = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft   = ['vim']

[[plugins]] # deoplete source for vim-lsp
repo    = 'lighttiger2505/deoplete-vim-lsp'
depends = ['deoplete.nvim']
on_i    = 1


#  Utils
#-----------------------------------------------
[[plugins]] # dark powered asynchronous unite all interfaces for neovim/vim8
repo   = 'Shougo/denite.nvim'
on_cmd = ['Denite']

[[plugins]] # hex editing system
repo   = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise', 'VinariseDump']

[[plugins]] # switch to the missing file without interaction
repo   = 'kana/vim-altr'
on_map = ['<Plug>(altr-']

[[plugins]] # A Git wrapper so awesome, it should be illegal
repo   = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Gbrowse']


#  Language
#-----------------------------------------------
[[plugins]] # syntax highlight for Haml
repo  = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]] # syntax highlight for Markdown
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]] # syntax highlight for CoffeeScript
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]] # syntax highlight for SCSS
repo  = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

# [[plugins]] # syntax highlight for Haskell
# repo  = 'kana/vim-filetype-haskell'
# on_ft = ['haskell']

[[plugins]] # Vastly improved Javascript indentation and syntax support
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]] # React JSX syntax pretty highlighting for vim
repo = 'maxmellon/vim-jsx-pretty'
on_ft = ['javascript', 'typescript']

[[plugins]] # TypesSript syntax files for Vim
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# [[plugins]] # Jade template engine syntax highlighting and indention
# repo  = 'digitaltoad/vim-jade'
# on_ft = ['jade']

[[plugins]] # Vim syntax highlighting for Google's Protocol Buffers
repo  = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]] # Vim syntax for TOML
repo  = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]] # vim syntax file for plantuml
repo  = 'aklt/plantuml-syntax'
on_ft = ['plantuml']

[[plugins]] # Vim configuration for Rust
repo  = 'rust-lang/rust.vim'
on_ft = ['rust']
