#  Editing
#-----------------------------------------------
[[plugins]] # define your own operator easily
repo  = 'kana/vim-operator-user'
on_if = 1

[[plugins]] # a simple, easy-to-use Vim alignment plugin
repo   = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']

[[plugins]] # operator to camelize/decamelize a specified text
repo    = 'tyru/operator-camelize.vim'
depends = ['vim-operator-user']
on_map = [
  '<Plug>(operator-camelize)',
  '<Plug>(operator-decamelize)',
  '<Plug>(operator-camelize-toggle)',
]

[[plugins]] # operator to replace text with register content
repo    = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
on_map  = ['<Plug>(operator-replace)']

[[plugins]] # insert several candidates with a single key
repo    = 'vim-scripts/smartchr'
on_func = ['smartchr']
on_i    = 1

[[plugins]] # switch segments of text with predefined replacements
repo   = 'AndrewRadev/switch.vim'
on_cmd = ['Swift']

[[plugins]] # maniplate selected text easily
repo   = 't9md/vim-textmanip'
on_map = ['<Plug>(textmanip-']

[[plugins]] # sequencial numbering with pattern
repo   = 'deris/vim-rengbang'
on_cmd = ['RengBang']


#  Completion
#-----------------------------------------------
[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_i    = 1
on_func = ['emmet']

[[plugins]] # lightweight snippet manager
repo = 'joereynolds/vim-minisnip'
on_i = 1

[[plugins]] # displays function signatures from completions in the command line
repo = 'Shougo/echodoc.vim'
on_i = 1
hook_source = '''
let g:echodoc#enable_at_startup = 1
'''

[[plugins]] # syntax source for neocomplete/deoplete/ncm
repo    = 'Shougo/neco-syntax'
depends = ['deoplete.nvim']
on_i    = 1
hook_source = '''
let g:necosyntax#min_keyword_length = 3
'''

[[plugins]] # deoplete source for vim-minisnip
repo    = 'joereynolds/deoplete-minisnip'
depends = ['deoplete.nvim', 'vim-minisnip']
on_i    = 1

[[plugins]] # vim source for neocomplete/deoplete
repo    = 'Shougo/neco-vim'
depends = ['deoplete.nvim']
on_ft   = ['vim']
on_i    = 1

[[plugins]] # asynchronous Go completion for Neovim. deoplete source for Go
repo    = 'zchee/deoplete-go'
depends = ['deoplete.nvim']
build   = 'make'
on_i    = 1
on_ft   = ['go']
hook_source = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
'''

[[plugins]] # deoplete.nvim source for c/c++/obj-c/obj-c++ with clang-python3
repo = 'zchee/deoplete-clang'
depends = ['deoplete.nvim']
on_i    = 1
on_ft   = ['c', 'cpp', 'objc', 'objcpp']

[[plugins]] # deoplete.nvim source for Ruby with solargraph
repo    = 'uplus/deoplete-solargraph'
depends = ['deoplete.nvim']
on_i    = 1
on_ft   = ['ruby']

# [[plugins]] # Language Server Protocol (LSP) support for vim and neovim
# repo    = 'autozimu/LanguageClient-neovim'
# rev     = 'next'
# build   = 'bash install.sh'
# depends = ['deoplete.nvim']


#  Utils
#-----------------------------------------------
[[plugins]] # dark powered asynchronous unite all interfaces for neovim/vim8
repo   = 'Shougo/denite.nvim'
on_cmd = ['Denite']

[[plugins]] # hex editing system
repo   = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise', 'VinariseDump']

[[plugins]] # switch to the missing file without interaction
repo   = 'kana/vim-altr'
on_map = ['<Plug>(altr-']


#  Language
#-----------------------------------------------
[[plugins]] # syntax highlight for Haml
repo  = 'tpope/vim-haml'
on_ft = ['haml']

[[plugins]] # syntax highlight for Markdown
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]] # syntax highlight for CoffeeScript
repo  = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

[[plugins]] # syntax highlight for SCSS
repo  = 'cakebaker/scss-syntax.vim'
on_ft = ['scss']

[[plugins]] # syntax highlight for Scala
repo  = 'derekwyatt/vim-scala'
on_ft = ['scala']
hook_source = '''
let g:scala_sort_across_groups = 1
'''

[[plugins]] # syntax highlight for Haskell
repo  = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]] # Vastly improved Javascript indentation and syntax support
repo  = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]] # TypesSript syntax files for Vim
repo  = 'leafgarland/typescript-vim'
on_ft = ['typescript']

[[plugins]] # Jade template engine syntax highlighting and indention
repo  = 'digitaltoad/vim-jade'
on_ft = ['jade']

[[plugins]] # vim syntax highlighting for ace templates
repo  = 'yosssi/vim-ace'
on_ft = ['ace']
