[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
hook_post_update = '''
  if dein#util#_is_windows()
    let cmd = 'tools\\update-dll-mingw'
  elseif dein#util#_is_cygwin()
    let cmd = 'make -f make_cygwin.mak'
  elseif executable('gmake')
    let cmd = 'gmake'
  else
    let cmd = 'make'
  endif
  let g:dein#plugin.build = cmd
'''


#  Editing
#-----------------------------------------------
[[plugins]]
# text objects for indented blocks of lines
repo    = 'kana/vim-textobj-indent'
depends = ['kana/vim-textobj-user']

[[plugins]]
# adds text-objects for word-based columns
repo = 'coderifous/textobj-word-column.vim'

[[plugins]]
# deleting, changing, and adding surroundings
repo = 'surround.vim'

[[plugins]]
# f/t motions to highlight all possible choices
repo = 'Lokaltog/vim-easymotion'

[[plugins]]
# commenting code
repo   = 'scrooloose/nerdcommenter'
on_map = [['n', 'gc'], ['v', 'gc']]

[[plugins]]
# general quickrun-hook plugins
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
# update status line
repo = 'KazuakiM/vim-qfstatusline'

[[plugins]]
# highlight quickfix errors
repo = 'cohama/vim-hier'

[[plugins]]
# see quickfix, location list and Syntastic lists errors and warnings
repo = 'dannyob/quickfixstatus'

[[plugins]]
# mark syntax error lines
repo = 'KazuakiM/vim-qfsigns'

[[plugins]]
# async syntax checking
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
# extended % matching
repo = 'tmhedberg/matchit'

[[plugins]]
# auto close parentheses and repeat by dot
repo    = 'cohama/lexima.vim'
depends = ['smartchr', 'Shougo/neocomplete', 'Shougo/neosnippet']

[[plugins]]
# pasting with indentation adjusted to paste destination
repo = 'sickill/vim-pasta'

[[plugins]]
# a genius template engine
repo = 'creasty/mold.vim'


#  Utils
#-----------------------------------------------
[[plugins]]
# unite and create user interfaces
repo   = 'Shougo/unite.vim'
on_cmd = ['Unite']
lazy   = 1

[[plugins]]
# a Git wrapper so awesome
repo = 'tpope/vim-fugitive'

[[plugins]]
# enable repeating supported plugin maps with dot
repo = 'tpope/vim-repeat'

[[plugins]]
# a tree explorer
repo = 'scrooloose/nerdtree'

[[plugins]]
# pseudo clipboard register
repo = 'kana/vim-fakeclip'

[[plugins]]
# run commands quickly
repo = 'thinca/vim-quickrun'

[[plugins]]
# create your own submodes
repo = 'kana/vim-submode'

[[plugins]]
# substitute preview
repo   = 'osyo-manga/vim-over'
on_cmd = ['OverCommandLine']

[[plugins]]
# ctags generator
repo = 'szw/vim-tags'


#  Appearance
#-----------------------------------------------
[[plugins]]
# toggle, display and navigate marks
repo = 'kshenoy/vim-signature'

[[plugins]]
# search status
repo   = 'osyo-manga/vim-anzu'
on_map = ['<Plug>(anzu-']

[[plugins]]
# candle theme
repo = 'creasty/candle.vim'


#  Language
#-----------------------------------------------
[[plugins]]
# React JSX syntax highlighting and indenting
repo = 'mxw/vim-jsx'
