python_versions:
  - 2.7.3
  - 3.5.0

packages:
  - { name: 'aws-shell', extra_args: '--ignore-installed six' }
  - awscli
  - glances
  - locustio
  - misaka
  - mitmproxy
  - numpy
  - pgcli
  - protobuf
  - pyamf
  - pygments
  - tornado
