python_versions:
  - '2.7'
  - '3'

packages:
  - aws-shell --ignore-installed six
  - awscli
  - glances
  - locustio
  - misaka
  - mitmproxy
  - numpy
  - pgcli
  - protobuf
  - pyamf
  - pygments
  - tornado
