-- Command-line helpers (user/cmdline.lua today, plus abbreviations).
local t = require('t')
local describe, it = t.describe, t.it

local function cmdline(nvim)
  return { nvim:call('getcmdline'), nvim:call('getcmdpos') }
end

--- Command line text with the cursor marked by `|`.
local function cmdline_with_cursor(nvim)
  local line, pos = unpack(cmdline(nvim))
  return line:sub(1, pos - 1) .. '|' .. line:sub(pos)
end

describe('Command line', function()
  describe('shortcuts', function()
    it("' at the start inserts the visual range '<,'>", function()
      local nvim = t.nvim()
      nvim:type(":'")
      t.eq("'<,'>|", cmdline_with_cursor(nvim))
    end)

    it(':w!! becomes a sudo write', function()
      local nvim = t.nvim()
      nvim:type(':w!!')
      t.eq('w !sudo tee % > /dev/null|', cmdline_with_cursor(nvim))
    end)

    it(":ee edits relative to the current file's directory", function()
      local nvim = t.nvim()
      nvim:edit('dir/file.txt', { 'x' })
      nvim:type(':ee')
      t.eq('e ' .. nvim:path('dir') .. '/|', cmdline_with_cursor(nvim))
    end)

    it(':ef edits the current file path', function()
      local nvim = t.nvim()
      nvim:edit('dir/file.txt', { 'x' })
      nvim:type(':ef')
      t.eq('e ' .. nvim:path('dir/file.txt') .. '|', cmdline_with_cursor(nvim))
    end)

    it(':er renames the current file', function()
      local nvim = t.nvim()
      nvim:edit('dir/file.txt', { 'x' })
      nvim:type(':er')
      t.eq('Rename ' .. nvim:path('dir/file.txt') .. '|', cmdline_with_cursor(nvim))
    end)

    it(':eh / :eg / :ev start from home / ~/go/src/github.com / $VIMRUNTIME', function()
      local nvim = t.nvim()
      nvim:type(':eh')
      t.eq('e ~/|', cmdline_with_cursor(nvim))
      nvim:type('<C-u><BS>:eg')
      t.eq('e ~/go/src/github.com/|', cmdline_with_cursor(nvim))
      nvim:type('<C-u><BS>:ev')
      t.eq('e ' .. nvim:eval('$VIMRUNTIME') .. '/|', cmdline_with_cursor(nvim))
    end)
  end)

  describe('substitute', function()
    it(':s/ expands to s/\\v|//g', function()
      local nvim = t.nvim()
      nvim:type(':s/')
      t.eq('s/\\v|//g', cmdline_with_cursor(nvim))
    end)

    it('works after % and the visual range', function()
      local nvim = t.nvim()
      nvim:type(':%s/')
      t.eq('%s/\\v|//g', cmdline_with_cursor(nvim))
      nvim:type('<Esc>')
      nvim:set_buffer({ '|a', 'b' })
      nvim:type('Vj:s/')
      t.eq("'<,'>s/\\v|//g", cmdline_with_cursor(nvim))
    end)

    for _, delim in ipairs({ '~', '!', '@', '#', '%', ':' }) do
      it(('accepts %s as the delimiter'):format(delim), function()
        local nvim = t.nvim()
        nvim:type(':s' .. delim)
        t.eq(('s%s\\v|%s%sg'):format(delim, delim, delim), cmdline_with_cursor(nvim))
      end)
    end

    it(':sc/ is case sensitive, :si/ case insensitive', function()
      local nvim = t.nvim()
      nvim:type(':sc/')
      t.eq('s/\\C\\v|//g', cmdline_with_cursor(nvim))
      nvim:type('<Esc>:si/')
      t.eq('s/\\c\\v|//g', cmdline_with_cursor(nvim))
    end)

    it(':sm/ starts a case-preserving :Subs', function()
      local nvim = t.nvim()
      nvim:type(':sm/')
      t.eq('Subs/|/', cmdline_with_cursor(nvim))
    end)

    it(':s/ then typing the pattern and replacement substitutes globally in very-magic mode', function()
      local nvim = t.nvim()
      nvim:set_buffer('|foo(1) foo(2)')
      nvim:type(':s/foo\\((\\d)\\)<Right>bar\\1<CR>')
      t.eq({ 'bar1 bar2' }, nvim:lines())
    end)

    it(':Subs replaces while preserving each case variant', function()
      local nvim = t.nvim()
      nvim:set_buffer('|fooBar FooBar foo_bar FOO_BAR')
      nvim:type(':sm/foo_bar<Right>baz_qux<CR>')
      t.eq({ 'bazQux BazQux baz_qux BAZ_QUX' }, nvim:lines())
    end)
  end)

  describe('search', function()
    it('/ inside a / search is escaped', function()
      local nvim = t.nvim()
      nvim:type('/a/b')
      t.eq('a\\/b', nvim:call('getcmdline'))
      nvim:type('<Esc>/c\\/')
      t.eq('c\\/', nvim:call('getcmdline'), 'an explicit \\/ is kept as is')
    end)

    it('? inside a ? search is escaped', function()
      local nvim = t.nvim()
      nvim:type('?a?b')
      t.eq('a\\?b', nvim:call('getcmdline'))
    end)
  end)

  describe('abbreviations', function()
    for alias, filetype in pairs({ js = 'javascript', jsx = 'javascriptreact', ts = 'typescript', tsx = 'typescriptreact', md = 'markdown', bq = 'sql.bq', pg = 'sql.pg' }) do
      it((':setf %s sets filetype %s'):format(alias, filetype), function()
        local nvim = t.nvim()
        nvim:type(':setf ' .. alias .. '<CR>')
        t.eq(filetype, nvim:filetype())
        nvim:type(':setfiletype ' .. alias .. '<CR>')
        t.eq(filetype, nvim:filetype())
      end)
    end
  end)

  describe('live preview commands', function()
    it(':Norm previews on screen while typing and applies on <CR>', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|a', 'b' })
      nvim:type(':%Norm A!')
      local screen = table.concat(nvim:screen(), '\n')
      t.match('1 a!', screen, 'preview of line 1')
      t.match('2 b!', screen, 'preview of line 2')
      t.eq({ 'a', 'b' }, nvim:lines(), 'the buffer is untouched until <CR>')
      nvim:type('<CR>')
      t.eq({ 'a!', 'b!' }, nvim:lines())
      nvim:type(':%Norm Ax<Esc>')
      t.eq({ 'a!', 'b!' }, nvim:lines(), 'cancelled preview is not applied')
    end)

    it(':G and :V work like :g and :v', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|keep 1', 'drop', 'keep 2' })
      nvim:type(':G/drop/d<CR>')
      t.eq({ 'keep 1', 'keep 2' }, nvim:lines())
      nvim:set_buffer({ '|keep 1', 'drop', 'keep 2' })
      nvim:type(':V/keep/d<CR>')
      t.eq({ 'keep 1', 'keep 2' }, nvim:lines())
    end)
  end)
end)
