local t = require('t')
local describe, it = t.describe, t.it

describe('Editing keys', function()
  describe('motion', function()
    it('j/k move by display line through a wrapped line', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|' .. string.rep('word ', 60), 'next' })
      nvim:type('j')
      local row, col = unpack(nvim:cursor())
      t.eq(1, row, 'j stays on the wrapped line')
      t.ok(col > 50, 'j moved to the next screen line')
      nvim:type('k')
      t.eq({ 1, 0 }, nvim:cursor())
      nvim:type('vj')
      t.eq(1, nvim:cursor()[1], 'visual j also moves by display line')
    end)

    it('<Space>h / <Space>l jump to the first non-blank / end of the screen line', function()
      local nvim = t.nvim()
      nvim:set_buffer('    foo b|ar baz')
      nvim:type('<Space>h')
      t.buffer(nvim, '    |foo bar baz')
      nvim:type('<Space>l')
      t.buffer(nvim, '    foo bar ba|z')
      nvim:type('0v<Space>l')
      t.eq('v', nvim:mode())
      t.buffer(nvim, '    foo bar baz|', 'in visual mode it selects through the end of the line')
    end)

    it('ge / gE repeat as a submode: `gee` goes back two word ends', function()
      local nvim = t.nvim()
      nvim:set_buffer('one two three fou|r')
      nvim:type('ge')
      t.buffer(nvim, 'one two thre|e four')
      nvim:set_buffer('one two three fou|r')
      nvim:type('gee')
      t.buffer(nvim, 'one tw|o three four')
      nvim:set_buffer('a.b c.d e.f g.|h')
      nvim:type('gEE')
      t.buffer(nvim, 'a.b c.|d e.f g.h')
    end)

    it("'[ / `[ go to the start of the last yank, past the marks on the way", function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'l1', '|l2', 'l3', 'l4', 'l5', 'l6' })
      nvim:type('ma3jmbkyy2j')
      nvim:type("'[")
      t.eq(4, nvim:cursor()[1])
      nvim:type('G`[')
      t.eq(4, nvim:cursor()[1])
    end)
  end)

  describe('registers', function()
    it('x, X and visual x delete without touching the unnamed register', function()
      local nvim = t.nvim()
      nvim:set_buffer('|keep abcdef')
      nvim:type('yiw')
      nvim:type('wx')
      t.buffer(nvim, 'keep |bcdef')
      nvim:type('X')
      t.buffer(nvim, 'keep|bcdef')
      nvim:type('lvlx')
      t.eq({ 'keepbef' }, nvim:lines())
      t.eq('keep', nvim:getreg('"'))
    end)

    it('c, C and visual c change without touching the unnamed register', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|keep', 'one two', 'three four', 'five six' })
      nvim:type('yiw')
      nvim:type('jciwONE<Esc>')
      nvim:type('j0CTHREE<Esc>')
      nvim:type('j0vecFIVE<Esc>')
      t.eq({ 'keep', 'ONE two', 'THREE', 'FIVE six' }, nvim:lines())
      t.eq('keep', nvim:getreg('"'))
    end)

    it('d still yanks (only x and c are redirected to the black hole)', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|first', 'second' })
      nvim:type('dd')
      t.eq('first\n', nvim:getreg('"'))
    end)

    it('yanks go to the system clipboard (clipboard=unnamed)', function()
      local nvim = t.nvim()
      nvim:set_buffer('|hello world')
      nvim:type('yiw')
      t.eq('hello', nvim:getreg('*'))
    end)
  end)

  describe('undo-friendly repeats', function()
    it('repeated x is undone in one step', function()
      local nvim = t.nvim()
      nvim:set_buffer('|abcdef')
      nvim:type('xxx')
      t.buffer(nvim, '|def')
      nvim:type('u')
      t.eq({ 'abcdef' }, nvim:lines())
    end)

    it('repeated <C-a>/<C-x> is undone in one step', function()
      local nvim = t.nvim()
      nvim:set_buffer('n |10')
      nvim:type('<C-a><C-a><C-a>')
      t.eq({ 'n 13' }, nvim:lines())
      nvim:type('u')
      t.eq({ 'n 10' }, nvim:lines())
      nvim:type('<C-a><C-a><C-x>')
      t.eq({ 'n 11' }, nvim:lines(), '<C-x> continues the same repeat')
      nvim:type('u')
      t.eq({ 'n 10' }, nvim:lines())
    end)

    it('a pause ends the <C-a> repeat (the next one is a separate undo step)', function()
      local nvim = t.nvim()
      nvim:set_buffer('n |10')
      nvim:type('<C-a><C-a>')
      nvim:type('<C-a>')
      t.eq({ 'n 13' }, nvim:lines())
      nvim:type('u')
      t.eq({ 'n 12' }, nvim:lines())
    end)

    it('<C-a> increments letters and treats leading zeros as decimal (nrformats=alpha)', function()
      local nvim = t.nvim()
      nvim:set_buffer('|n 007')
      nvim:type('<C-a>')
      t.eq({ 'o 007' }, nvim:lines())
      nvim:type('w<C-a>')
      t.eq({ 'o 008' }, nvim:lines())
    end)
  end)

  describe('lines', function()
    it('J joins lines without moving the cursor', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'f|oo', '  bar' })
      nvim:type('J')
      t.buffer(nvim, 'f|oo bar')
    end)

    it('<Space>J splits the line after the character under the cursor', function()
      local nvim = t.nvim()
      nvim:set_buffer('foo| bar')
      nvim:type('<Space>J')
      t.eq({ 'foo ', 'bar' }, nvim:lines())
      nvim:set_buffer('foo|bar')
      nvim:type('<Space>J')
      t.eq({ 'foob', 'ar' }, nvim:lines())
    end)

    it(']<Space> / [<Space> add a blank line below / above and stay in normal mode', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'a', 'b|c', 'd' })
      nvim:type(']<Space>')
      t.eq('n', nvim:mode())
      t.buffer(nvim, { 'a', 'b|c', '', 'd' })
      nvim:type('[<Space>')
      t.buffer(nvim, { 'a', '', 'b|c', '', 'd' })
    end)

    it('visual < and > keep the selection for repeated shifting', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|a', 'b' })
      nvim:type('Vj>>')
      t.eq('V', nvim:mode())
      t.eq({ '    a', '    b' }, nvim:lines())
      nvim:type('<lt>')
      t.eq({ '  a', '  b' }, nvim:lines())
    end)

    it('<C-s>h / <C-s>l outdent / indent in insert mode', function()
      local nvim = t.nvim()
      nvim:set_buffer('|foo')
      nvim:type('A<C-s>l')
      t.eq({ '  foo' }, nvim:lines())
      nvim:type('<C-s><C-l>')
      t.eq({ '    foo' }, nvim:lines())
      nvim:type('<C-s>h')
      t.eq({ '  foo' }, nvim:lines())
      nvim:type('<C-s><C-h>')
      t.eq({ 'foo' }, nvim:lines())
      t.eq('i', nvim:mode())
    end)
  end)

  describe('selection', function()
    it('gp reselects the last pasted text', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|one', 'two' })
      nvim:type('yyjp')
      nvim:type('gg0gp')
      t.eq('V', nvim:mode())
      t.eq(3, nvim:call('line', 'v'))
      t.eq(3, nvim:cursor()[1])
    end)

    it('<Space>a selects the whole buffer', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'one', 't|wo', 'three' })
      nvim:type('<Space>a')
      t.eq('V', nvim:mode())
      t.eq(1, nvim:call('line', 'v'))
      t.eq(3, nvim:cursor()[1])
    end)
  end)

  describe('substitute', function()
    it('visual <Space>s starts :%s with the escaped selection', function()
      local nvim = t.nvim()
      nvim:set_buffer('x |a.b/c y')
      nvim:type('vt<Space><Space>s')
      t.eq('c', nvim:mode())
      t.eq('%s/a\\.b\\/c/', nvim:call('getcmdline'))
      nvim:type('Z<CR>')
      t.eq({ 'x Z y' }, nvim:lines())
    end)

    it('<Space>* starts :%s for the whole word under the cursor', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'f|oo foobar foo' })
      nvim:type('<Space>*')
      t.eq('%s/\\<foo\\>/', nvim:call('getcmdline'))
      nvim:type('X/g<CR>')
      t.eq({ 'X foobar X' }, nvim:lines())
    end)
  end)

  describe('paste', function()
    it('<C-v> pastes the clipboard in insert, command-line and select mode', function()
      local nvim = t.nvim()
      nvim:call('setreg', '*', 'clip')
      nvim:set_buffer('|')
      nvim:type('i<C-v><Esc>')
      t.eq({ 'clip' }, nvim:lines())
      nvim:type(':<C-v>')
      t.eq('clip', nvim:call('getcmdline'))
      nvim:type('<Esc>')
      nvim:set_buffer('|foo bar')
      nvim:type('ve<C-g><C-v><Esc>')
      t.eq({ 'clip bar' }, nvim:lines())
    end)

    it('<C-\\> inserts the next key literally (the original <C-v>)', function()
      local nvim = t.nvim()
      -- (the first i and : load plugins, so the keys can land a moment after
      -- type() returns)
      nvim:type('i<C-\\><Tab><Esc>')
      nvim:wait_for(function()
        return nvim:line(1) ~= ''
      end, { message = 'the typed keys' })
      t.eq({ '\t' }, nvim:lines())
      nvim:type(':<C-\\><Tab>')
      nvim:wait_for(function()
        return nvim:call('getcmdline') ~= ''
      end, { message = 'the typed keys' })
      t.eq('\t', nvim:call('getcmdline'))
    end)
  end)

  describe('disabled keys', function()
    it('ZQ does not quit', function()
      local nvim = t.nvim()
      nvim:type('ZQ')
      t.eq('n', nvim:mode())
    end)

    it('visual K does nothing', function()
      local nvim = t.nvim()
      nvim:set_buffer('|printf')
      nvim:type('veK')
      t.eq('v', nvim:mode())
      t.eq(1, #nvim:request('nvim_list_wins'))
    end)
  end)

  describe('tags', function()
    local function tags_project(nvim)
      nvim:files({
        ['a.c'] = { 'int foo() { return 0; }' },
        ['b.c'] = { 'static int foo() { return 1; }', 'void bar() { foo(); }' },
        ['tags'] = {
          '!_TAG_FILE_SORTED\t1\t/0=unsorted, 1=sorted, 2=foldcase/',
          'bar\tb.c\t/^void bar() { foo(); }$/;"\tf\tlanguage:C',
          'foo\ta.c\t/^int foo() { return 0; }$/;"\tf\tlanguage:C',
          'foo\tb.c\t/^static int foo() { return 1; }$/;"\tf\tlanguage:C\tfile:',
        },
      })
    end

    -- (in Neovim's order, :help tag-priority: the static tag of the current
    -- file before the global one of another)
    it('<C-]> lists all matches, the current file\'s first', function()
      local nvim = t.nvim()
      tags_project(nvim)
      nvim:edit('b.c')
      nvim:set_cursor(2, 13)
      nvim:type('<C-]>1<CR>')
      t.eq('b.c', nvim:call('expand', '%:t'))
      t.eq({ 1, 0 }, nvim:cursor())
    end)

    it(']t / [t walk through the matches', function()
      local nvim = t.nvim()
      tags_project(nvim)
      nvim:edit('b.c')
      nvim:set_cursor(2, 13)
      nvim:type('<C-]>1<CR>')
      nvim:type(']t')
      t.eq('a.c', nvim:call('expand', '%:t'))
      nvim:type('[t')
      t.eq('b.c', nvim:call('expand', '%:t'))
    end)
  end)
end)
