local t = require('t')
local describe, it = t.describe, t.it

describe('Emacs-style keys', function()
  describe('insert mode', function()
    it('<C-a> / <C-e> go to the start / end of the line', function()
      local nvim = t.nvim()
      nvim:set_buffer('  foo b|ar')
      nvim:type('i<C-a>')
      t.buffer(nvim, '|  foo bar')
      nvim:type('<C-e>')
      t.buffer(nvim, '  foo bar|')
      t.eq('i', nvim:mode())
    end)

    it('<C-a> right after the first character just moves left', function()
      local nvim = t.nvim()
      nvim:set_buffer('ab|c')
      nvim:type('i<Left><C-a>')
      t.buffer(nvim, '|abc')
    end)

    it('<C-b> / <C-f> move left / right', function()
      local nvim = t.nvim()
      nvim:set_buffer('ab|cd')
      nvim:type('i<C-b>')
      t.buffer(nvim, 'a|bcd')
      nvim:type('<C-f><C-f>')
      t.buffer(nvim, 'abc|d')
    end)

    it('<C-d> deletes the character under the cursor, <C-h> the one before', function()
      local nvim = t.nvim()
      nvim:set_buffer('ab|cd')
      nvim:type('i<C-d>')
      t.buffer(nvim, 'ab|d')
      nvim:type('<C-h>')
      t.buffer(nvim, 'a|d')
    end)

    it('<C-k> kills to the end of the line, or joins the next line at the end', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'foo| bar', 'baz' })
      nvim:type('i<C-k>')
      t.buffer(nvim, { 'foo|', 'baz' })
      nvim:type('<C-k>')
      t.buffer(nvim, { 'foo|baz' })
      t.eq('i', nvim:mode())
    end)

    it('<C-t> transposes the characters around the cursor', function()
      local nvim = t.nvim()
      nvim:set_buffer('ab|c')
      nvim:type('i<C-t>')
      t.buffer(nvim, 'ac|b')
      t.eq('i', nvim:mode())
    end)

    it('<C-p> / <C-n> move up / down by display line without leaving insert mode', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'one', 'tw|o', 'three' })
      nvim:type('i<C-p>')
      t.buffer(nvim, { 'on|e', 'two', 'three' })
      nvim:type('<C-n><C-n>')
      t.buffer(nvim, { 'one', 'two', 'th|ree' })
      t.eq('i', nvim:mode())
    end)

    it('<C-p> / <C-n> keep the column across a shorter line', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'abcdef|gh', 'ab', 'abcdefgh' })
      nvim:type('i<C-n>')
      t.buffer(nvim, { 'abcdefgh', 'ab|', 'abcdefgh' })
      nvim:type('<C-n>')
      t.buffer(nvim, { 'abcdefgh', 'ab', 'abcdef|gh' })
    end)

    it("<C-n> / <C-p> / <C-e> / <C-a> / <C-k>, held, keep insert mode's cursor in the terminal", function()
      -- (they run their command through normal mode, whose block cursor would flash)
      local nvim = t.nvim({ tui = true })
      local lines = {}
      for i = 1, 20 do
        lines[i] = 'line ' .. i
      end
      nvim:set_buffer(lines)
      nvim:wait_output()
      local from = #nvim.output + 1
      nvim:type('i')
      --- Holds `key` down, at the key repeat nix/modules/macos.nix sets (16.7 ms).
      local function hold(key, repeats)
        for _ = 1, repeats do
          nvim:type(key, { settle = false })
          nvim:sleep(17)
        end
        nvim:settle()
      end
      hold('<C-n>', 10)
      t.eq({ 11, 0 }, nvim:cursor())
      hold('<C-p>', 5)
      t.eq({ 6, 0 }, nvim:cursor())
      hold('<C-e>', 3)
      t.eq({ 6, 6 }, nvim:cursor())
      hold('<C-a>', 3)
      t.eq({ 6, 0 }, nvim:cursor())
      hold('<C-k>', 2)
      t.eq({ 'line 5', 'line 7', 'line 8' }, { nvim:line(5), nvim:line(6), nvim:line(7) })
      t.eq('i', nvim:mode())
      nvim:wait_output()
      local shapes = nvim:cursor_shapes(from)
      t.contains(shapes, 'bar')
      t.eq({}, vim.tbl_filter(function(shape)
        return shape ~= 'bar'
      end, shapes), "cursor shapes other than insert mode's bar")
    end, { timeout = 30000 })

    it('<C-j> is <CR> and <C-c> is <Esc>', function()
      local nvim = t.nvim()
      nvim:type('ifoo<C-j>bar<C-c>')
      t.eq({ 'foo', 'bar' }, nvim:lines())
      t.eq('n', nvim:mode())
    end)
  end)

  describe('normal mode', function()
    it('<C-j> is <CR> (next line) and <C-c> is <Esc>', function()
      local nvim = t.nvim()
      nvim:set_buffer({ 'o|ne', '  two' })
      nvim:type('<C-j>')
      t.buffer(nvim, { 'one', '  |two' })
      nvim:type('d<C-c>')
      t.eq('n', nvim:mode())
      t.eq({ 'one', '  two' }, nvim:lines())
    end)
  end)

  describe('command line', function()
    it('supports <C-a> <C-b> <C-f> <C-d> <C-h> <C-k>', function()
      local nvim = t.nvim()
      nvim:type(':abcdef')
      nvim:type('<C-a>')
      t.eq(1, nvim:call('getcmdpos'))
      nvim:type('<C-f><C-f>')
      t.eq(3, nvim:call('getcmdpos'))
      nvim:type('<C-d>')
      t.eq('abdef', nvim:call('getcmdline'))
      nvim:type('<C-h>')
      t.eq('adef', nvim:call('getcmdline'))
      nvim:type('<C-f><C-k>')
      t.eq('ad', nvim:call('getcmdline'))
      nvim:type('<C-b>')
      t.eq(2, nvim:call('getcmdpos'))
    end)

    it('<C-c> cancels the command line', function()
      local nvim = t.nvim()
      nvim:type(':echo<C-c>')
      t.eq('n', nvim:mode())
    end)
  end)

  describe('select mode', function()
    it('<C-e> / <C-f> insert at the end of the selection', function()
      local nvim = t.nvim()
      nvim:set_buffer('|foo bar')
      nvim:type('vl<C-g>')
      t.eq('s', nvim:mode())
      nvim:type('<C-e>X<Esc>')
      t.eq({ 'foXo bar' }, nvim:lines())
      nvim:set_buffer('|foo bar')
      nvim:type('vl<C-g><C-f>Y<Esc>')
      t.eq({ 'foYo bar' }, nvim:lines())
    end)

    it('<C-a> / <C-b> insert at the start of the selection', function()
      local nvim = t.nvim()
      nvim:set_buffer('foo |bar')
      nvim:type('vl<C-g><C-a>X<Esc>')
      t.eq({ 'foo Xbar' }, nvim:lines())
      nvim:set_buffer('foo |bar')
      nvim:type('vl<C-g><C-b>Y<Esc>')
      t.eq({ 'foo Ybar' }, nvim:lines())
    end)

    it('<C-d> deletes the selection and <C-c> leaves select mode', function()
      local nvim = t.nvim()
      nvim:set_buffer('|foo bar')
      nvim:type('vl<C-g><C-d>')
      t.eq({ 'o bar' }, nvim:lines())
      nvim:type('<Esc>')
      nvim:type('vl<C-g><C-c>')
      t.eq('n', nvim:mode())
    end)
  end)
end)
