-- Files: auto-save, whitespace, directories, rename/delete, detection,
-- last position, sibling navigation, buffer commands.
local t = require('t')
local describe, it = t.describe, t.it

describe('Files', function()
  describe('auto-save', function()
    it('saves after a change in normal mode', function()
      local nvim = t.nvim()
      nvim:edit('a.txt', { 'hello world' })
      nvim:type('x')
      nvim:wait_for(function()
        return (nvim:read_file('a.txt') or {})[1] == 'ello world'
      end)
      t.eq(0, nvim:eval('&modified'))
    end)

    it('saves when leaving insert mode, not while typing', function()
      local nvim = t.nvim()
      nvim:edit('a.txt', { 'hello' })
      nvim:type('A world')
      nvim:sleep(300)
      t.eq({ 'hello' }, nvim:read_file('a.txt'), 'not saved while in insert mode')
      nvim:type('<Esc>')
      nvim:wait_for(function()
        return (nvim:read_file('a.txt') or {})[1] == 'hello world'
      end)
    end)

    it('saves when leaving the buffer or losing focus', function()
      local nvim = t.nvim()
      nvim:files({ ['a.txt'] = { 'a' }, ['b.txt'] = { 'b' } })
      nvim:edit('a.txt')
      nvim:set_buffer('changed a')
      nvim:cmd('edit b.txt')
      t.eq({ 'changed a' }, nvim:read_file('a.txt'))
      nvim:set_buffer('changed b')
      nvim:cmd('doautocmd FocusLost')
      t.eq({ 'changed b' }, nvim:read_file('b.txt'))
    end)

    it('does not save readonly or special buffers', function()
      local nvim = t.nvim()
      nvim:edit('ro.txt', { 'ro' })
      nvim:cmd('setlocal readonly')
      nvim:type('x')
      nvim:sleep(200)
      t.eq({ 'ro' }, nvim:read_file('ro.txt'))
      nvim:cmd('enew | setlocal buftype=nofile')
      nvim:type('ix<Esc>')
      t.eq('', nvim:eval('v:errmsg'):match('E382') or '', 'no attempt to write a nofile buffer')
    end)

    it(':AutoSaveToggle turns it off and on', function()
      local nvim = t.nvim()
      nvim:edit('a.txt', { 'abc' })
      t.eq('AutoSave is OFF', vim.trim(nvim:exec('AutoSaveToggle')))
      nvim:type('x')
      nvim:sleep(200)
      t.eq({ 'abc' }, nvim:read_file('a.txt'))
      t.eq('AutoSave is ON', vim.trim(nvim:exec('AutoSaveToggle')))
      nvim:type('x')
      nvim:wait_for(function()
        return (nvim:read_file('a.txt') or {})[1] == 'c'
      end)
    end)

    it('keeps the `[ `] marks of the last change', function()
      local nvim = t.nvim()
      nvim:edit('a.txt', { 'one', 'two', 'three' })
      nvim:type('jyyp')
      nvim:wait_for(function()
        return #(nvim:read_file('a.txt') or {}) == 4
      end)
      t.eq(3, nvim:call('line', "'["))
      t.eq(3, nvim:call('line', "']"))
    end)
  end)

  describe('trailing whitespace', function()
    it('is stripped when leaving insert mode, keeping the cursor', function()
      local nvim = t.nvim()
      nvim:edit('a.txt', { 'keep  ', 'x' })
      nvim:type('jA  <Esc>')
      nvim:wait_for(function()
        return nvim:lines()[2] == 'x'
      end)
      t.eq({ 'keep', 'x' }, nvim:lines())
      t.eq({ 2, 0 }, nvim:cursor())
    end)

    it('is kept in special buffers', function()
      local nvim = t.nvim()
      nvim:cmd('setlocal buftype=nofile')
      nvim:type('ix  <Esc>')
      nvim:sleep(300)
      t.eq({ 'x  ' }, nvim:lines())
    end)
  end)

  it('writing creates missing directories', function()
    local nvim = t.nvim()
    nvim:cmd('edit deep/new/dir/file.txt')
    nvim:set_buffer('x')
    nvim:cmd('write')
    t.eq({ 'x' }, nvim:read_file('deep/new/dir/file.txt'))
  end)

  it('detects the filetype of a new buffer when it is saved', function()
    local nvim = t.nvim()
    nvim:set_buffer({ '#!/bin/bash', 'echo hi' })
    t.eq('', nvim:filetype())
    nvim:cmd('write script')
    t.eq('sh', nvim:filetype())
  end)

  it('reopening a file restores the last cursor position', function()
    -- Neovim keeps no marks for files in /tmp or /private ('shada' r items), and the sandbox can be in either: macOS's
    -- temporary directory is in /private
    local keep_marks = { '--cmd', 'set shada-=r/tmp/ shada-=r/private/' }
    local nvim = t.nvim({ shada = 'shada', args = keep_marks })
    local shada = nvim:path('shada')
    nvim:edit('a.txt', { '1', '2', '3', '4', '5' })
    nvim:type('4G')
    nvim:cmd('wshada! ' .. shada)
    nvim:close()
    local again = t.nvim({ cwd = nvim.dir, shada = shada, args = keep_marks })
    again:edit('a.txt')
    t.eq(4, again:cursor()[1])
  end)

  describe(':Rename / :Delete', function()
    it(':Rename moves the file (creating directories) and keeps editing it', function()
      local nvim = t.nvim()
      nvim:edit('old.txt', { 'content' })
      nvim:cmd('Rename sub/new.txt')
      t.eq(nvim:path('sub/new.txt'), nvim:bufname())
      t.no(nvim:exists('old.txt'))
      t.eq({ 'content' }, nvim:read_file('sub/new.txt'))
    end)

    it(':Rename writes a buffer that was never saved', function()
      local nvim = t.nvim()
      nvim:set_buffer('fresh')
      nvim:cmd('Rename fresh.txt')
      t.eq({ 'fresh' }, nvim:read_file('fresh.txt'))
    end)

    it(':Delete moves the file to the Trash and closes its buffer', function()
      local nvim = t.nvim()
      nvim:edit('doomed.txt', { 'bye' })
      nvim:cmd('Delete')
      nvim:wait_for(function()
        return not nvim:exists('doomed.txt')
      end)
      t.eq('', nvim:bufname())
      t.eq(1, vim.fn.filereadable(nvim.ctx.trash_dir .. '/doomed.txt'))
    end)
  end)

  describe('siblings', function()
    it('g) / g( edit the next / previous file in the same directory, wrapping around', function()
      local nvim = t.nvim()
      nvim:files({ ['d/a.txt'] = 'a', ['d/b.txt'] = 'b', ['d/c.txt'] = 'c', ['d/sub/x.txt'] = 'x' })
      nvim:edit('d/b.txt')
      nvim:type('g)')
      t.eq('c.txt', nvim:call('expand', '%:t'))
      nvim:type('g)')
      t.eq('a.txt', nvim:call('expand', '%:t'), 'wraps, skipping directories')
      nvim:type('g(')
      t.eq('c.txt', nvim:call('expand', '%:t'))
    end)
  end)

  describe('buffers', function()
    it(':CleanBuffers wipes hidden buffers, keeping the current, alternate and modified ones', function()
      local nvim = t.nvim()
      nvim:files({ ['a.txt'] = 'a', ['b.txt'] = 'b', ['c.txt'] = 'c', ['d.txt'] = 'd' })
      nvim:cmd('AutoSaveToggle')
      nvim:edit('a.txt')
      nvim:edit('b.txt')
      nvim:set_buffer('modified')
      nvim:edit('c.txt')
      nvim:cmd('silent! edit! d.txt')
      nvim:cmd('buffer c.txt')
      nvim:cmd('CleanBuffers')
      local names = nvim:lua([[
        local names = {}
        for _, b in ipairs(vim.api.nvim_list_bufs()) do
          if vim.bo[b].buflisted then
            names[#names + 1] = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(b), ':t')
          end
        end
        table.sort(names)
        return names
      ]])
      t.eq({ 'b.txt', 'c.txt', 'd.txt' }, names)
    end)

    it(':Encoding reopens the file with another encoding', function()
      local nvim = t.nvim()
      vim.fn.writefile({ '\130\160' }, nvim:path('sjis.txt'))
      nvim:edit('sjis.txt')
      nvim:cmd('Encoding sjis')
      t.eq('sjis', nvim:eval('&fileencoding'))
      t.eq({ 'あ' }, nvim:lines())
      t.contains(nvim:call('EncodingNameComplete', 'euc', ':Encoding euc', 13), 'euc-jp')
    end)

    it(':SoftTab / :HardTab change the indentation style', function()
      local nvim = t.nvim()
      nvim:cmd('SoftTab 4')
      t.eq({ 1, 4, 4 }, nvim:eval('[&l:expandtab, &l:tabstop, &l:shiftwidth]'))
      nvim:cmd('HardTab 8')
      t.eq({ 0, 8, 8 }, nvim:eval('[&l:expandtab, &l:tabstop, &l:shiftwidth]'))
    end)

    it(':Capture inserts the output of a command below the cursor', function()
      local nvim = t.nvim()
      nvim:set_buffer('|first')
      nvim:cmd('Capture echo "a" | echo "b"')
      t.eq({ 'first', 'a', 'b' }, vim.tbl_filter(function(l)
        return l ~= ''
      end, nvim:lines()))
    end)
  end)
end)
