-- How the pieces cooperate: places where typing must stay "dumb" (no
-- auto-pairs, completion or AI), and blockwise insert from any visual mode.
local t = require('t')
local probe = require('probe')
local describe, it = t.describe, t.it

describe('Integration', function()
  describe('I / A on a visual selection', function()
    it('I on a characterwise or linewise selection inserts on every line', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|one', 'two', 'three' })
      nvim:type('Vjj')
      nvim:type('I// <Esc>')
      t.eq({ '// one', '// two', '// three' }, nvim:lines())
      nvim:set_buffer({ 'x|one', 'xtwo', 'xthree' })
      nvim:type('vjj')
      nvim:type('I- <Esc>')
      t.eq({ 'x- one', 'x- two', 'x- three' }, nvim:lines())
    end)

    it('A on a linewise selection appends at the end of every line', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|a', 'bb', 'ccc' })
      nvim:type('Vjj')
      nvim:type('A;<Esc>')
      t.eq({ 'a;', 'bb;', 'ccc;' }, nvim:lines())
    end)

    it('while inserting, brackets are not auto-closed and no menu or AI shows up', function()
      local nvim = t.nvim()
      nvim:files({ ['.git/'] = true })
      nvim:edit('main.go', { 'package main', '', 'e2eAlpha()', 'e2eBeta()' })
      probe.wait_lsp(nvim)
      nvim:type('3GVj')
      nvim:type('Ifoo(e2e')
      probe.assert_no_completion(nvim, 800)
      t.eq('', probe.ghost_text(nvim))
      nvim:type('<Esc>')
      t.eq({ 'foo(e2ee2eAlpha()', 'foo(e2ee2eBeta()' }, { nvim:line(3), nvim:line(4) })
    end)

    it('auto-pairs are back once the blockwise insert is over', function()
      local nvim = t.nvim()
      nvim:set_buffer({ '|a', 'b' })
      nvim:type('VjI(<Esc>')
      t.eq({ '(a', '(b' }, nvim:lines())
      nvim:type('Gox(')
      t.match('x%(%)$', nvim:line(3))
    end)
  end)

  describe('picker prompt', function()
    local function prompt(nvim)
      nvim:files({ ['.git/'] = true, ['a.txt'] = { 'x' } })
      probe.wait_picker_ready(nvim)
      nvim:type('<C-q>')
      probe.wait_picker(nvim)
      t.eq('ddu-ff-filter', nvim:filetype())
    end

    it('does not auto-close brackets', function()
      local nvim = t.nvim()
      prompt(nvim)
      nvim:type('(')
      t.eq('(', nvim:line(1))
    end)

    it('does not show the completion menu', function()
      local nvim = t.nvim()
      prompt(nvim)
      nvim:type('a.t')
      probe.assert_no_completion(nvim, 800)
    end)

    it('does not show AI suggestions', function()
      local nvim = t.nvim()
      prompt(nvim)
      nvim:type('The quick brown ')
      nvim:sleep(1000)
      t.eq('', probe.ghost_text(nvim))
    end)
  end)
end)
