#  Editing
#-----------------------------------------------
[[plugins]] # define your own operator easily
repo = 'kana/vim-operator-user'

[[plugins]] # operator to replace text with register content
repo = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
on_map = ['<Plug>(operator-replace)']
hook_add = '''
nmap r <Plug>(operator-replace)
xmap r <Plug>(operator-replace)
omap r <Plug>(operator-replace)
nnoremap R r
xnoremap R r
onoremap R r
'''

[[plugins]] # a simple, easy-to-use Vim alignment plugin
repo = 'junegunn/vim-easy-align'
on_map = ['<Plug>(EasyAlign)']
hook_add = '''
xmap <silent> L <Plug>(EasyAlign)
'''

[[plugins]] # auto close parentheses and repeat by dot
repo = 'cohama/lexima.vim'
on_func = ['lexima#']
on_event = ['InsertEnter', 'CmdlineEnter']
hook_add = '''
let g:lexima_map_escape = ''
let g:lexima_enable_endwise_rules = 0
let g:lexima_disable_on_nofile = 1
'''
hook_source = '''
call user#plugin#lexima#init()
'''

[[plugins]] # maniplate selected text easily
repo = 't9md/vim-textmanip'
on_map = ['<Plug>(textmanip-']
hook_add = '''
let g:textmanip_enable_mappings = 0

let g:textmanip_hooks = {}
function! g:textmanip_hooks.finish(tm) abort
  let l:tm = a:tm
  let l:helper = textmanip#helper#get()
  if !l:tm.linewise
    call l:helper.remove_trailing_WS(l:tm)
  endif
endfunction

xnoremap <SID>(tm) <Nop>
xnoremap <script> m <SID>(tm)
xnoremap <script> <SID>(tm)m <SID>(tm)

xmap <SID>(tm)j <Plug>(textmanip-move-down)<SID>(tm)
xmap <SID>(tm)k <Plug>(textmanip-move-up)<SID>(tm)
xmap <SID>(tm)h <Plug>(textmanip-move-left)<SID>(tm)
xmap <SID>(tm)l <Plug>(textmanip-move-right)<SID>(tm)
xmap <SID>(tm)J <Plug>(textmanip-duplicate-down)<SID>(tm)
xmap <SID>(tm)K <Plug>(textmanip-duplicate-up)<SID>(tm)
xmap <SID>(tm)H <Plug>(textmanip-duplicate-left)<SID>(tm)
xmap <SID>(tm)L <Plug>(textmanip-duplicate-right)<SID>(tm)
'''

[[plugins]] # Neovim motions on speed!
repo = 'phaazon/hop.nvim'
on_cmd = ['HopChar1']
hook_add = '''
nnoremap s <Cmd>HopChar1<CR>
'''
hook_source = '''
lua require'hop'.setup()
'''

[[plugins]] # Neovim plugin for GitHub Copilot
repo = 'github/copilot.vim'
rev = 'release'
on_event = ['InsertEnter']
on_cmd = ['Copilot']
on_func = ['copilot#']
hook_add = '''
let g:copilot_no_tab_map = v:true
let g:copilot_assume_mapped = v:true
let g:copilot_idle_delay = 200
'''

[[plugins]] # The easiest way to create previewable commands in Neovim.
repo = 'smjonas/live-command.nvim'
on_event = ['CmdlineEnter']
hook_source = '''
lua << EOF
require("live-command").setup {
  commands = {
    Norm = { cmd = "norm" },
    G = { cmd = "g" },
    V = { cmd = "v" },
  },
}
EOF
'''

[[plugins]] # An all in one plugin for converting text case in Neovim
repo = 'johmsalas/text-case.nvim'
on_cmd = ['Subs']
on_lua = ['textcase']
hook_add = '''
nnoremap <silent> ge_ <Cmd>lua require('textcase').operator('to_snake_case')<CR>
nnoremap <silent> ge- <Cmd>lua require('textcase').operator('to_dash_case')<CR>
nnoremap <silent> ge. <Cmd>lua require('textcase').operator('to_dot_case')<CR>
nnoremap <silent> ge/ <Cmd>lua require('textcase').operator('to_path_case')<CR>
nnoremap <silent> gec <Cmd>lua require('textcase').operator('to_camel_case')<CR>
nnoremap <silent> gep <Cmd>lua require('textcase').operator('to_pascal_case')<CR>
nnoremap <silent> gek <Cmd>lua require('textcase').operator('to_constant_case')<CR>

xnoremap <silent> ge_ <Cmd>lua require('textcase').visual('to_snake_case')<CR>
xnoremap <silent> ge- <Cmd>lua require('textcase').visual('to_dash_case')<CR>
xnoremap <silent> ge. <Cmd>lua require('textcase').visual('to_dot_case')<CR>
xnoremap <silent> ge/ <Cmd>lua require('textcase').visual('to_path_case')<CR>
xnoremap <silent> gec <Cmd>lua require('textcase').visual('to_camel_case')<CR>
xnoremap <silent> gep <Cmd>lua require('textcase').visual('to_pascal_case')<CR>
xnoremap <silent> gek <Cmd>lua require('textcase').visual('to_constant_case')<CR>
'''

#  Navigation
#-----------------------------------------------
[[plugins]] # switch to the missing file without interaction
repo = 'kana/vim-altr'
on_map = ['<Plug>(altr-']
hook_source = '''
call user#plugin#altr#lazy_init()
'''
hook_add = '''
nmap ga <Plug>(altr-forward)
nmap gA <Plug>(altr-back)
'''

[[plugins]] # A Git wrapper so awesome, it should be illegal
repo = 'tpope/vim-fugitive'
on_cmd = ['Git', 'GBrowse']
hook_add = '''
let g:fugitive_browse_handlers = [function('user#plugin#fugitive#browse_handler')]
command! -nargs=0 GBlame :Git blame
'''
