version: 2.1

jobs:
  provisioning:
    parameters:
      up-opts:
        type: string
    macos:
      xcode: 12.4.0 # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
    environment:
      HOMEBREW_VERBOSE: 1
      DOTFILES_NOEDIT_SECRETS: 1
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: up
          command: ./up << parameters.up-opts >> -vvvv
          no_output_timeout: 90m

workflows:
  main:
    jobs:
      - provisioning:
          name: provisioning-lib
          up-opts: --tags=base,install.homebrew.formula
      - provisioning:
          name: provisioning-lang
          up-opts: --tags=base,lang
      - provisioning:
          name: provisioning-app
          up-opts: --tags=install,app,system --skip-tags=install.homebrew.formula
