version: 2.1

jobs:
  build:
    macos:
      xcode: 12.4.0 # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
    environment:
      HOMEBREW_VERBOSE: 1
      DOTFILES_NOEDIT_SECRETS: 1
      SKIP_TAGS: zsh
    working_directory: ~/dotfiles
    steps:
      - checkout
      - run:
          name: Provisioning
          command: ./up --skip-tags="$SKIP_TAGS" -vvvv
