- name: install dependencies
  community.general.homebrew:
    name:
      - libyaml
      - openssl@3
      - zlib
    state: latest

- name: get openssl dir
  ansible.builtin.command: |
    bash -lc 'brew --prefix openssl@3'
  register: openssl_dir

- name: get libyaml dir
  ansible.builtin.command: |
    bash -lc 'brew --prefix libyaml'
  register: libyaml_dir

- name: get zlib dir
  ansible.builtin.command: |
    bash -lc 'brew --prefix zlib'
  register: zlib_dir

# Versions are in config/mise/config.toml, which also installs config/mise/default-gems
# @see https://gist.github.com/Neutrollized/37841827940b28b27ec2e54abbbcc408
- name: install ruby
  ansible.builtin.command: |
    bash -lc 'mise install ruby'
  environment:
    CFLAGS: '-Wno-error=implicit-function-declaration'
    RUBY_CONFIGURE_OPTS: '--with-openssl-dir={{ openssl_dir.stdout | quote }} --with-libyaml-dir={{ libyaml_dir.stdout | quote }} --with-zlib-dir={{ zlib_dir.stdout | quote }}'

- name: install solargraph
  ansible.builtin.command: |
    bash -lc 'gem install solargraph'
