- set_fact:
    ruby: {}

- name: check rbenv
  command: |
    bash -lc 'which rbenv'
  register: which_rbenv
  ignore_errors: yes

- name: install rbenv
  command: |
    bash -lc 'anyenv install rbenv'
  when: which_rbenv.rc > 0

- name: install plugins
  git:
    repo: 'https://github.com/{{ item }}.git'
    dest: '{{ anyenv.envs_dir }}/rbenv/plugins/{{ item | basename }}'
  with_items: '{{ ruby.plugins }}'
  when: ruby.plugins

- name: copy default-gems
  file:
    src:  '{{ ruby.default_gems_path }}'
    dest: '{{ anyenv.envs_dir }}/rbenv/default-gems'
    state: link
    force: yes

- name: clear init script cache
  file:
    dest: '{{ item }}'
    state: absent
  with_fileglob:
    - '{{ home_path }}/.anyenv-init-*'

- name: get installed versions
  command: |
    bash -lc 'rbenv versions'
  register: installed_versions

- name: install dependency
  homebrew:
    name:
      - ruby-build
      - readline
      - openssl@3
      - libyaml
      - zlib
    state: present

- name: get openssl dir
  command: |
    bash -lc 'brew --prefix openssl@3'
  register: openssl_dir

- name: get readline dir
  command: |
    bash -lc 'brew --prefix readline'
  register: readline_dir

- name: get libyaml dir
  command: |
    bash -lc 'brew --prefix libyaml'
  register: libyaml_dir

- name: get zlib dir
  command: |
    bash -lc 'brew --prefix zlib'
  register: zlib_dir

# @see https://gist.github.com/Neutrollized/37841827940b28b27ec2e54abbbcc408
- name: install ruby
  command: |
    bash -lc 'rbenv install {{ item | quote }}'
  environment:
    CFLAGS: '-Wno-error=implicit-function-declaration'
    RUBY_CONFIGURE_OPTS: '--with-openssl-dir={{ openssl_dir.stdout | quote }} --with-readline-dir={{ readline_dir.stdout | quote }} --with-libyaml-dir={{ libyaml_dir.stdout | quote }} --with-zlib-dir={{ zlib_dir.stdout | quote }}'
  when: |
    ruby.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ ruby.versions }}'

- name: set global ruby
  command: |
    bash -lc 'rbenv global {{ ruby.versions[0] | quote }}'
  when: ruby.versions

- name: install solargraph
  command: |
    bash -lc 'gem install solargraph'
