- set_fact:
    ruby: {}

- name: check rbenv
  command: |
    which rbenv
  register: which_rbenv
  ignore_errors: yes

- name: install rbenv
  command: |
    anyenv install rbenv
  when: which_rbenv.rc > 0

- name: install plugins
  git:
    repo: 'https://github.com/{{ item }}.git'
    dest: '{{ ruby.plugins_dir }}/{{ item }}'
  with_items: '{{ ruby.plugins }}'
  when: ruby.plugins_dir and ruby.plugins

- name: get installed versions
  command: |
    rbenv versions
  register: installed_versions

- name: install ruby
  command: |
    rbenv install '{{ item }}'
  when: |
    ruby.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ ruby.versions }}'

- name: set global ruby
  command: |
    rbenv global '{{ ruby.versions[0] }}'
  when: ruby.versions
