- set_fact:
    homebrew: {}

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: add registries
  homebrew_tap:
    name:  '{{ item }}'
    state: present
  with_items: '{{ homebrew.registries }}'

- name: install cask applications
  homebrew_cask:
    name:  '{{ item }}'
    state: latest
    accept_external_apps: yes
    sudo_password: '{{ ansible_become_pass }}'
  with_items: '{{ homebrew.applications }}'
  when: homebrew.applications
  ignore_errors: yes
  tags: install.homebrew.cask

- name: install homebrew packages
  homebrew:
    name:  '{{ homebrew.packages }}'
    state: latest
  when: homebrew.packages
  tags: install.homebrew.formula
