- set_fact:
    homebrew: {}

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: install cask applications
  homebrew_cask:
    name:  '{{ item }}'
    state: present
    accept_external_apps: yes
  with_items: '{{ homebrew.applications }}'
  when: homebrew.applications
  ignore_errors: yes
  tags: install.homebrew.cask

- name: install homebrew packages
  homebrew:
    name:  '{{ homebrew.packages }}'
    state: present
  when: homebrew.packages
  tags: install.homebrew.formula
