- ansible.builtin.set_fact:
    homebrew: {}

- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: add tap registries
  community.general.homebrew_tap:
    name:  '{{ item }}'
    state: present
    trust: true # otherwise Homebrew ignores the tap unless a formula/cask is named explicitly
  loop: '{{ homebrew.taps | default([]) }}'
  tags: install.homebrew.tap

- name: install casks
  community.general.homebrew_cask:
    name:  '{{ item }}'
    state: latest
    accept_external_apps: true
    sudo_password: '{{ ansible_become_pass }}'
  loop: '{{ homebrew.casks | default([]) }}'
  ignore_errors: true
  tags: install.homebrew.cask

- name: install formulas
  community.general.homebrew:
    name:  '{{ homebrew.formulas }}'
    state: latest
  when: homebrew.formulas is defined
  tags: install.homebrew.formula
