- set_fact:
    homebrew: {}

- name: update homebrew
  homebrew:
    update_homebrew: yes

- name: tap external homebrew repos
  homebrew_tap:
    tap:   '{{ item }}'
    state: present
  with_items: '{{ homebrew.repositories }}'
  when: homebrew.repositories

- name: install cask applications
  homebrew_cask:
    name:  '{{ item }}'
    state: present
    accept_external_apps: yes
  with_items: '{{ homebrew.applications }}'
  when: homebrew.applications

- name: install homebrew packages
  homebrew:
    name:  '{{ homebrew.packages }}'
    state: present
  when: homebrew.packages
