- ansible.builtin.set_fact:
    homebrew: {}

- name: update homebrew
  community.general.homebrew:
    update_homebrew: true

- name: add tap registries
  community.general.homebrew_tap:
    name:  '{{ item }}'
    state: present
    trust: true # Homebrew ignores formulae and casks of untrusted third-party taps
  loop: '{{ homebrew.taps }}'
  when: homebrew.taps is defined
  tags: install.homebrew.tap

- name: install casks
  community.general.homebrew_cask:
    name:  '{{ item }}'
    state: latest
    accept_external_apps: true
    sudo_password: '{{ ansible_become_pass }}'
  loop: '{{ homebrew.casks }}'
  when: homebrew.casks is defined
  ignore_errors: true
  tags: install.homebrew.cask

- name: install formulas
  community.general.homebrew:
    name:  '{{ homebrew.formulas }}'
    state: latest
  when: homebrew.formulas is defined
  tags: install.homebrew.formula
