- name: update software
  command: |
    sudo '{{ tex.texlive_bin_path }}/tlmgr' update --self --all

- name: copy texmf
  copy:
    src:  texmf.cnf
    dest: '{{ tex.texlive_texmr_path }}/web2c/texmf.cnf'

- name: configure texmf
  command: |
    '{{ tex.texlive_bin_path }}/mktexlsr'
  become: yes

- name: setup tex to use hiragino fonts
  command: |
    perl cjk-gs-integrate.pl --link-texmf --force
    mktexlsr
    updmap-sys --setoption kanjiEmbed hiragino-elcapitan-pron
  args:
    chdir: '{{ tex.texlive_path }}/2015/texmf-dist/scripts/cjk-gs-integrate'
  environment:
    PATH: '{{ ansible_env.PATH }}:{{ tex.texlive_bin_path }}'

  become: yes

- name: make bst/bib directories
  file:
    dest:    '{{ item }}'
    state:   directory
    recurse: yes
  with_items:
    - '{{ home_path }}/Library/texmf/bibtex/bib'
    - '{{ home_path }}/Library/texmf/bibtex/bst'
    - '{{ home_path }}/Library/texmf/tex/latex'
