- name: update software
  command: |
    sudo '{{ texlive_bin_path }}/tlmgr' update --self --all

- name: copy texmf
  copy:
    src:  '{{ dotfiles_path }}/tex/texmf.cnf'
    dest: '{{ texlive_texmr_path }}/web2c/texmf.cnf'

- name: configure texmf
  command: |
    '{{ texlive_bin_path }}/mktexlsr'
  become: True

- name: setup tex to use hiragino fonts
  command: |
    perl cjk-gs-integrate.pl --link-texmf --force
    mktexlsr
    updmap-sys --setoption kanjiEmbed hiragino-elcapitan-pron
  args:
    chdir: '{{ texlive_path }}/2015/texmf-dist/scripts/cjk-gs-integrate'
  become: True

- name: make bst/bib directories
  file:
    dest:    '{{ item }}'
    state:   directory
    recurse: True
  with_items:
    - '{{ home_path }}/Library/texmf/bibtex/bib'
    - '{{ home_path }}/Library/texmf/bibtex/bst'
    - '{{ home_path }}/Library/texmf/tex/latex'
