[[plugins]] # dark powered vim/neovim plugin manager
repo = 'Shougo/dein.vim'

#  Editing
#-----------------------------------------------
[[plugins]] # create your own text objects
repo = 'kana/vim-textobj-user'

[[plugins]] # text objects for indented blocks of lines
repo = 'kana/vim-textobj-indent'
depends = ['vim-textobj-user']

[[plugins]] # text objects for multiple types of parentheses
repo = 'osyo-manga/vim-textobj-multiblock'
depends = ['vim-textobj-user']

[[plugins]] # Text objects for numbers
repo = 'tkhren/vim-textobj-numeral'
depends = ['vim-textobj-user']

[[plugins]] # deleting, changing, and adding surroundings
repo = 'tpope/vim-surround'

[[plugins]] # pasting with indentation adjusted to paste destination
repo = 'sickill/vim-pasta'

[[plugins]] # a genius template engine
repo = 'creasty/mold.vim'

[[plugins]] # The ultimate snippet solution for Vim
repo = 'SirVer/ultisnips'

[[plugins]] # auto close parentheses and repeat by dot
repo = 'cohama/lexima.vim'
hook_add = '''
call vimrc#plugin#lexima#init()
'''

[[plugins]] # enable repeating supported plugin maps with dot
repo = 'tpope/vim-repeat'

[[plugins]] # create your own submodes
repo = 'kana/vim-submode'
hook_add = '''
call vimrc#plugin#submode#init()
'''

[[plugins]] # run commands quickly
repo = 'thinca/vim-quickrun'

[[plugins]] # Intellisense engine for Vim8 & Neovim, full language server protocol support as VSCode
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = 0
hook_add = '''
call vimrc#plugin#coc#init()
'''

[[plugins]] # switch segments of text with predefined replacements
repo = 'AndrewRadev/switch.vim'

[[plugins]] # sequencial numbering with pattern
repo = 'deris/vim-rengbang'
hook_add = '''
let g:rengbang_default_usefirst = 1
let g:rengbang_default_pattern = '\(\<\d\+\>\)'
'''

[[plugins]] # Neovim/Vim plugin for easy async search and replace across multiple files
repo = 'eugen0329/vim-esearch'
hook_add = '''
let g:esearch = {}
let g:esearch.regex = 1
let g:esearch.textobj = 0
let g:esearch.case = 'smart'
'''

[[plugins]] # EditorConfig Vim Plugin
repo = 'editorconfig/editorconfig-vim'
hook_add = '''
let g:EditorConfig_exclude_patterns = ['fugitive://.*', 'scp://.*']
'''

[[plugins]] # Treesitter configurations and abstraction layer for Neovim
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
hook_post_update = '''
:TSUpdate
'''

#  UI
#-----------------------------------------------
[[plugins]] # toggle, display and navigate marks
repo = 'kshenoy/vim-signature'
hook_add = '''
let g:SignatureIncludeMarks = 'abcdefghijklmnopqrtuvwxyz'
let g:SignatureMarkTextHL = 'Statement'
'''

[[plugins]] # search status
repo = 'osyo-manga/vim-anzu'

[[plugins]] # Highlight the current search result differently
repo = 'qxxxb/vim-searchhi'

[[plugins]] # a tree explorer
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDSpaceDelims = 1
let g:NERDShutUp = 1
let g:NERDTreeShowHidden = 1
let g:NERDTreeIgnore = ['\~$', '\.git$']
let g:NERDTreeAutoDeleteBuffer = 1
'''
