#  Editing
#-----------------------------------------------
[[plugins]] # define your own operator easily
repo  = 'kana/vim-operator-user'
on_if = 1

[[plugins]] # operator to camelize/decamelize a specified text
repo    = 'tyru/operator-camelize.vim'
depends = ['vim-operator-user']
on_map = [
  '<Plug>(operator-camelize)',
  '<Plug>(operator-decamelize)',
  '<Plug>(operator-camelize-toggle)',
]

[[plugins]] # operator to replace text with register content
repo    = 'kana/vim-operator-replace'
depends = ['vim-operator-user']
on_map  = ['<Plug>(operator-replace)']

[[plugins]] # a simple, easy-to-use Vim alignment plugin
repo   = 'junegunn/vim-easy-align'
on_cmd = ['EasyAlign']

[[plugins]] # insert several candidates with a single key
repo    = 'kana/vim-smartchr'
on_func = ['smartchr']

[[plugins]] # maniplate selected text easily
repo   = 't9md/vim-textmanip'
on_map = ['<Plug>(textmanip-']

[[plugins]] # emmet for vim: HTML and CSS hi-speed coding
repo    = 'mattn/emmet-vim'
on_func = ['emmet']
hook_add = '''
let g:user_emmet_install_global = 0
let g:user_emmet_mode = 'i'
let g:user_emmet_leader_key = '<Nop>'
'''

[[plugins]] # Vim motions on speed!
repo    = 'easymotion/vim-easymotion'
on_func = ['EasyMotion#S']

[[plugins]] # A Vim text editor plugin to swap delimited items
repo   = 'machakann/vim-swap'
on_map = ['<Plug>(swap-']

[[plugins]] # hex editing system
repo   = 'Shougo/vinarise.vim'
on_cmd = ['Vinarise', 'VinariseDump']

[[plugins]] # Use treesitter to autoclose and autorename html tag
repo = 'windwp/nvim-ts-autotag'
on_ft = [
  'html',
  'javascript', 'javascriptreact', 'jsx',
  'typescript', 'typescriptreact', 'tsx',
  'handlebars','hbs',
]

#  Navigation
#-----------------------------------------------
[[plugins]] # dark powered asynchronous unite all interfaces for neovim/vim8
repo   = 'Shougo/denite.nvim'
on_cmd = ['Denite']

[[plugins]] # switch to the missing file without interaction
repo   = 'kana/vim-altr'
on_map = ['<Plug>(altr-']

[[plugins]] # A Git wrapper so awesome, it should be illegal
repo   = 'tpope/vim-fugitive'
on_cmd = ['Gblame', 'Gbrowse']

[[plugins]] # An implementation of the Popup API from vim in Neovim
repo = 'nvim-lua/popup.nvim'

[[plugins]] # All the lua functions I don't want to write twice
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo      = 'fannheyward/telescope-coc.nvim'
on_source = ['telescope.nvim']

[[plugins]] # Gaze deeply into unknown regions using the power of the moon
repo    = 'nvim-telescope/telescope.nvim'
depends = ['popup.nvim', 'plenary.nvim']
on_cmd  = ['Telescope']
hook_add = '''
lua require("creasty.plugins.telescope")
'''

#  Util
#-----------------------------------------------
[[plugins]] # Neovim Treesitter Playground
repo   = 'nvim-treesitter/playground'
on_cmd = ['TSPlaygroundToggle', 'TSHighlightCapturesUnderCursor']

#  Language
#-----------------------------------------------
[[plugins]] # syntax highlight for Markdown
repo  = 'tpope/vim-markdown'
on_ft = ['markdown']

[[plugins]] # Vim syntax highlighting for Google's Protocol Buffers
repo  = 'uarun/vim-protobuf'
on_ft = ['proto']

[[plugins]] # vim syntax file for plantuml
repo  = 'aklt/plantuml-syntax'
on_ft = ['plantuml']
