- set_fact:
    zsh_bin: '{{ brew_bin_path }}/zsh'

- name: install zsh
  homebrew:
    name:  zsh
    state: latest

- name: add zsh to /etc/shells
  lineinfile:
    dest: /etc/shells
    line: '{{ zsh_bin }}'
  become: yes

- name: check presence of /etc/zshenv
  stat: path=/etc/zshenv
  register: zshenv_stat

- name: Rename /etc/zshenv
  command: |
    sudo mv /etc/zshenv /etc/_zshenv
  when: zshenv_stat.stat.exists

- name: change login shell to zsh
  command: |
    chpass -s '{{ zsh_bin }}'
  become: yes
  register: chpass_result
  until: chpass_result.rc == 0
  retries: 3
  when: |
    lookup("env", "SHELL") != zsh_bin
