- ansible.builtin.set_fact:
    link: {}

- name: allocate parent directories
  ansible.builtin.file:
    dest:    '{{ home_path }}/{{ item }}'
    state:   directory
    recurse: true
  loop_control:
    label: '~/{{ item }}'
  when: item != ""
  loop: '{{ link.values() | map("dirname") | unique | list }}'

- name: check destinations
  ansible.builtin.stat:
    path: '{{ home_path }}/{{ item.value }}'
  loop_control:
    label: '{{ item.value }}'
  loop: '{{ link | dict2items }}'
  register: dest_stat

- name: create backup files
  ansible.builtin.command: |
    mv -f \
      {{ home_path | quote }}/{{ item.item.value | quote }} \
      {{ home_path | quote }}/{{ item.item.value | quote }}.bak
  when: item.stat.exists and not item.stat.islnk
  loop_control:
    label: '{{ item.item.value }}'
  loop: '{{ dest_stat.results }}'

- name: create symlinks
  ansible.builtin.file:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ home_path }}/{{ item.value }}'
    state: link
    force: true
  loop_control:
    label: '{{ item.value }}'
  loop: '{{ link | dict2items }}'
