- set_fact:
    link: {}

- name: create symlinks
  file:
    src:   '{{ dotfiles_path }}/{{ item.key }}'
    dest:  '{{ home_path }}/{{ item.value }}'
    state: link
  with_dict: '{{ link }}'
  when: link
