- ansible.builtin.set_fact:
    rust: {}

- name: install rustup
  community.general.homebrew:
    name:  rustup
    state: latest

- name: install toolchain
  ansible.builtin.command: |
    bash -lc 'rustup default stable'

- name: rustup update
  ansible.builtin.command: |
    bash -lc 'rustup update'

- name: install components
  ansible.builtin.command: |
    bash -lc 'rustup component add {{ item }}'
  loop:
    - clippy        # https://github.com/rust-lang/rust-clippy
    - rust-src      # https://github.com/rust-lang/rust
    - rust-analyzer # https://github.com/rust-lang/rust-analyzer
