- set_fact:
    rust: {}

- name: install rustup
  homebrew:
    name:  rustup
    state: latest

- name: run rust-init
  command: |
    bash -lc 'rustup-init  -v -y --no-modify-path'

- name: rustup update
  command: |
    bash -lc 'rustup update'

- name: install components
  command: |
    bash -lc 'rustup component add {{ item }}'
  with_items:
    - clippy        # https://github.com/rust-lang/rust-clippy
    - rls           # https://github.com/rust-lang/rls
    - rust-analysis # https://github.com/rust-lang/rls
    - rust-src      # https://github.com/rust-lang/rust
