- set_fact:
    rust: {}

- name: install rustup
  homebrew:
    name:  rustup
    state: latest

- name: run rust-init
  command: |
    bash -lc 'rustup-init  -v -y --no-modify-path'

- name: rustup update
  command: |
    bash -lc 'rustup update'

- name: install components
  command: |
    bash -lc 'rustup update component add {{ item }}'
  with_items: '{{ rust.components }}'
  when: rust.components
