- set_fact:
    golang: {}

- name: install golang
  homebrew:
    name:  go
    state: present

- name: install packages
  command: |
     bash -lc 'go get -u {{ item | quote }}'
  with_items: '{{ golang.packages }}'
  when: golang.packages
