- set_fact:
    golang: {}

- name: install language
  homebrew:
    name:  go
    state: latest

- name: install tools
  homebrew:
    name:  '{{ item }}'
    state: latest
  with_items: '{{ golang.tools }}'
  when: golang.tools
