- set_fact:
    golang: {}

- name: install language
  homebrew:
    name:  go
    state: latest

- name: install tools (tap)
  homebrew:
    name:  '{{ item }}'
    state: present
  with_items:
    - golangci/tap # for golangci-lint

- name: install tools
  homebrew:
    name:  '{{ item }}'
    state: latest
  with_items:
    - golangci-lint # Fast linters runner for Go
    - gopls         # Language server for the Go language
