- ansible.builtin.set_fact:
    golang: {}

- name: install language
  community.general.homebrew:
    name:  go
    state: latest

- name: install tools (tap)
  community.general.homebrew_tap:
    name:  '{{ item }}'
    state: present
    trust: true
  loop:
    - golangci/tap # for golangci-lint

- name: install tools
  community.general.homebrew:
    name:
      - golangci/tap/golangci-lint # Fast linters runner for Go
      - gopls # Language server for the Go language
    state: latest
