- set_fact:
    golang: {}

- name: install golang
  homebrew:
    name:  go
    state: latest

- name: install dep
  homebrew:
    name:  dep
    state: present

- name: golangci-lint
  homebrew:
    name:  golangci/tap/golangci-lint
    state: present

- name: install commands
  command: |
     bash -lc 'go install {{ item | quote }}'
  with_items: '{{ golang.commands }}'
  when: golang.commands

#- block:
#    - name: optimize goimports | install
#      command: |
#        bash -lc 'go get -u {{ item | quote }}'
#      environment:
#        GO111MODULE: off
#      with_items:
#        - golang.org/x/tools/...
#        - github.com/monochromegane/dragon-imports/...
#        - github.com/pwaller/goimports-update-ignore
#    - name: optimize goimports | run goimports-update-ignore
#      command: |
#        bash -lc 'goimports-update-ignore -max-depth 5'
#    - name: optimize goimports | run dragon-imports
#      command: |
#        bash -lc 'dragon-imports'
