- set_fact:
    golang: {}

- name: install golang
  homebrew:
    name:  go
    state: latest

- name: install dep
  homebrew:
    name:  dep
    state: present

- block:
  - name: grapi | tap
    homebrew_tap:
      tap:   izumin5210/tools
      state: present
  - name: grapi | install
    homebrew:
      name:  izumin5210/tools/grapi
      state: present

- name: install packages
  command: |
     bash -lc 'go get -u {{ item | quote }}'
  environment:
    GO111MODULE: off
  with_items: '{{ golang.packages }}'
  when: golang.packages

- block:
    - name: optimize goimports | install
      command: |
        bash -lc 'go get -u {{ item | quote }}'
      environment:
        GO111MODULE: off
      with_items:
        - github.com/monochromegane/dragon-imports/...
        - github.com/pwaller/goimports-update-ignore
        - golang.org/x/tools/imports
    - name: optimize goimports | run goimports-update-ignore
      command: |
        bash -lc 'goimports-update-ignore -max-depth 5'
    - name: optimize goimports | run dragon-imports
      command: |
        bash -lc 'dragon-imports'
