- set_fact:
    golang: {}

- name: install golang
  homebrew:
    name:  go
    state: latest

- name: golangci-lint
  homebrew:
    name:  golangci/tap/golangci-lint
    state: present

- name: install commands
  command: |
     bash -lc 'go install {{ item | quote }}'
  with_items: '{{ golang.commands }}'
  when: golang.commands
