- set_fact:
    mas: {}

- name: install mas
  homebrew:
    name:  mas # Mac App Store command line interface
    state: present

- name: check if logged in
  command: |
    bash -lc 'mas account'
  ignore_errors: yes
  register: mas_logged_in

- name: install applications
  command: |
    bash -lc 'mas install {{ item | quote }}'
  with_items: '{{ mas.applications }}'
  when: mas.applications and mas_logged_in.get('rc') == 0

- name: upgrade applications
  command: |
    bash -lc 'mas upgrade'
  when: mas_logged_in.get('rc') == 0
