- set_fact:
    mas: {}

- name: signout mas
  command: |
    bash -ic 'mas signout'
  ignore_errors: yes

- name: signin to mas
  command: |
    bash -ic 'mas signin {{ mas.appstore_id | quote }} {{ mas.appstore_password | quote }}'
  ignore_errors: yes
  register: mas_signin
  when: mas.appstore_id and mas.appstore_password

- name: install applications
  command: |
    bash -ic 'mas install {{ item | quote }}'
  with_items: '{{ mas.applications }}'
  when: mas.applications and mas_signin.get('rc') == 0

- name: upgrade applications
  command: |
    bash -ic 'mas upgrade'
  when: mas_signin.get('rc') == 0
