- set_fact:
    mas: {}

- name: signout mas
  command: |
    mas signout
  ignore_errors: yes

- name: signin to mas
  command: |
    mas signin '{{ mas.appstore_id }}' '{{ mas.appstore_password }}'
  ignore_errors: yes
  register: mas_signin
  when: mas.appstore_id and mas.appstore_password

- name: install applications
  command: |
    mas install '{{ item }}'
  with_items: '{{ mas.applications }}'
  when: mas.applications and mas_signin.get('rc') == 0

- name: upgrade applications
  command: |
    mas upgrade
  when: mas_signin.get('rc') == 0
