words = [
    "autocmd",
    "autorun",
    "bignumber",
    "birthdate",
    "bitflag",
    "calculatable",
    "checkin",
    "circleci",
    "clearcoat",
    "cloudbuild",
    "cloudrun",
    "commentable",
    "comorbid",
    "creasty",
    "deeplink",
    "dein",
    "denite",
    "deno",
    "draftjs",
    "duplicatable",
    "envmap",
    "equirectangular",
    "evals",
    "finalizable",
    "fmap",
    "focusable",
    "frec",
    "frrf",
    "fullsize",
    "furigana",
    "gradlew",
    "graphviz",
    "henryapp",
    "hookable",
    "horiz",
    "inhouse",
    "keybind",
    "lanczos",
    "lerp",
    "ltrb",
    "metalness",
    "mhlw",
    "minmax",
    "modeless",
    "nvim",
    "openjdk",
    "outdent",
    "paleblue",
    "partialize",
    "partialized",
    "personalizable",
    "pnpm",
    "postdischarge",
    "prehospital",
    "promisified",
    "prosemirror",
    "raycaster",
    "respawn",
    "resubmittable",
    "riverpod",
    "schemafile",
    "signa",
    "strikethrough",
    "strval",
    "submatches",
    "tiptap",
    "tlaplus",
    "tweens",
    "typeparam",
    "uncancel",
    "undernutrition",
    "undoable",
    "unreads",
    "unwatch",
    "usecase",
    "validatable",
    "vercel",
    "ydoc",
    "yxml",
]
ignore_patterns = ['''\w+['’]\w+''']
min_word_length = 4
