# Versions are in config/mise/config.toml
- name: install nodejs
  ansible.builtin.command: |
    bash -lc 'mise install node'

- name: install default packages
  ansible.builtin.command: |
    bash -lc 'sed "s/#.*//" ~/.config/mise/default-npm-packages | xargs npm install -g'

- name: install yarn
  community.general.homebrew:
    name: yarn # JavaScript package manager
    state: latest
