- set_fact:
    nodejs: {}

- name: check ndenv
  command: |
    which ndenv
  register: which_ndenv
  ignore_errors: yes

- name: install ndenv
  command: |
    anyenv install ndenv
  when: which_ndenv.rc > 0

- name: get installed versions
  command: |
    ndenv versions
  register: installed_versions

- name: refresh anyenv
  command: |
    eval "$(anyenv init -)"
  when: which_ndenv.rc > 0

- name: install nodejs
  command: |
    ndenv install '{{ item }}'
  when: |
    nodejs.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ nodejs.versions }}'

- name: set global nodejs
  command: |
    ndenv global '{{ nodejs.versions[0] }}'
  when: nodejs.versions

- name: install npm packages
  npm:
    name:   '{{ item }}'
    global: yes
  with_items: '{{ nodejs.packages }}'
  when: nodejs.packages
