- set_fact:
    nodejs: {}

- name: check ndenv
  command: |
    bash -ic 'which ndenv'
  register: which_ndenv
  ignore_errors: yes

- name: install ndenv
  command: |
    bash -ic 'anyenv install ndenv'
  when: which_ndenv.rc > 0

- name: get installed versions
  command: |
    bash -ic 'ndenv versions'
  register: installed_versions

- name: install nodejs
  command: |
    bash -ic 'ndenv install {{ item | quote }}'
  when: |
    nodejs.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ nodejs.versions }}'

- name: set global nodejs
  command: |
    bash -ic 'ndenv global {{ nodejs.versions[0] | quote }}'
  when: nodejs.versions

- name: install npm packages
  npm:
    name:   '{{ item }}'
    global: yes
  with_items: '{{ nodejs.packages }}'
  when: nodejs.packages
