- set_fact:
    nodejs: {}

- name: check nodenv
  command: |
    bash -lc 'which nodenv'
  register: which_nodenv
  ignore_errors: yes

- name: install nodenv
  command: |
    bash -lc 'anyenv install -s nodenv'
  when: which_nodenv.rc > 0

- name: install plugins
  git:
    repo: 'https://github.com/{{ item }}.git'
    dest: '{{ anyenv.envs_dir }}/nodenv/plugins/{{ item | basename }}'
  with_items: '{{ nodejs.plugins }}'
  when: nodejs.plugins

- name: copy default-packages
  file:
    src:  '{{ nodejs.default_packages_path }}'
    dest: '{{ anyenv.envs_dir }}/nodenv/default-packages'
    state: link
    force: yes

- name: install nodejs
  command: |
    bash -lc 'nodenv install -s {{ item | quote }}'
  with_items: '{{ nodejs.versions }}'

- name: set global nodejs
  command: |
    bash -lc 'nodenv global {{ nodejs.versions[0] | quote }}'
  when: nodejs.versions

- name: install default packages
  command: |
    bash -lc 'nodenv default-packages install'

- name: install yarn
  homebrew:
    name: yarn # JavaScript package manager
    state: latest
