- set_fact:
    elixir: {}

- name: check exenv
  command: |
    bash -lc 'which exenv'
  register: which_exenv
  ignore_errors: yes

- name: install exenv
  command: |
    bash -lc 'anyenv install exenv'
  when: which_exenv.rc > 0

- name: get installed versions
  command: |
    bash -lc 'exenv versions'
  register: installed_versions

- name: install elixir
  command: |
    bash -lc 'exenv install {{ item | quote }}'
  when: |
    elixir.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ elixir.versions }}'

- name: set global elixir
  command: |
    bash -lc 'exenv global {{ elixir.versions[0] | quote }}'
  when: elixir.versions
