- ansible.builtin.set_fact:
    java: {}

- name: install openjdk
  community.general.homebrew:
    name:  '{{ java.versions }}'
    state: latest

- name: link
  ansible.builtin.file:
    src: '{{ homebrew_prefix }}/opt/{{ java.versions | first }}/libexec/openjdk.jdk'
    dest: /Library/Java/JavaVirtualMachines/openjdk.jdk
    state: link
    force: true
  become: true

# As `N` and `N.0`, the forms .java-version files written by jenv usually contain
- name: register java versions
  ansible.builtin.command: |
    bash -lc 'for v in {{ item | regex_replace("^openjdk@", "") }}{,.0}; do mise link --force "java@$v" "{{ homebrew_prefix }}/opt/{{ item }}/libexec/openjdk.jdk/Contents/Home"; done'
  loop: '{{ java.versions }}'

- name: install tools
  community.general.homebrew:
    name:
      - gradle                 # Open-source build automation tool based on the Groovy and Kotlin DSL
      - pre-commit             # Framework for managing multi-language pre-commit hooks
      - coursier               # Launcher for Coursier (required by pre-commit)
      - kotlin-language-server # Intelligent Kotlin support for any editor/IDE using the Language Server Protocol
    state: latest

# - name: install IDEs
#   homebrew_cask:
#     name:  '{{ item }}'
#     state: present
#   with_items:
#     - intellij-idea-ce
#     - android-sdk
#     - android-studio
