- name: check jenv
  command: |
    which jenv
  register: which_jenv
  ignore_errors: yes

- name: install jenv
  command: |
    anyenv install jenv
  when: which_jenv.rc > 0

- name: refresh anyenv
  command: |
    eval "$(anyenv init -)"
  when: which_jenv.rc > 0
