- set_fact:
    java: {}

- name: install openjdk
  homebrew:
    name: openjdk
    state: latest

- name: tap adoptopenjdk/openjdk
  homebrew_tap:
    tap:   adoptopenjdk/openjdk
    state: latest

- name: install old versions
  homebrew_cask:
    name: adoptopenjdk11
    state: latest

- name: check jenv
  command: |
    bash -lc 'which jenv'
  register: which_jenv
  ignore_errors: yes

- name: install jenv
  command: |
    bash -lc 'anyenv install jenv'
  when: which_jenv.rc > 0

- name: clear init script cache
  file:
    dest: '{{ item }}'
    state: absent
  with_fileglob:
    - '{{ anyenv.init_file_glob }}'

- name: enable export plugin
  command: |
    bash -lc 'jenv enable-plugin export'

- name: apply patch to export plugin
  patch:
    src: export_jenv_hook.zsh.patch
    dest: '{{ anyenv.envs_dir }}/jenv/plugins/export/etc/jenv.d/init/export_jenv_hook.zsh'

- name: register java home
  command: |
    bash -lc 'jenv add "$(/usr/libexec/java_home)"'

- name: install gradle
  homebrew:
    name:  gradle # Open-source build automation tool based on the Groovy and Kotlin DSL
    state: latest

# - name: install IDEs
#   homebrew:
#     name:  '{{ item }}'
#     state: latest
#   with_items:
#     - intellij-idea-ce
#     - android-sdk
#     - android-studio
