- set_fact:
    java: {}

- name: install openjdk
  homebrew:
    name: openjdk
    state: present

- name: tap adoptopenjdk/openjdk
  homebrew_tap:
    tap:   adoptopenjdk/openjdk
    state: present

- name: install old versions
  homebrew_cask:
    name: adoptopenjdk11
    state: present

- name: check jenv
  command: |
    bash -lc 'which jenv'
  register: which_jenv
  ignore_errors: yes

- name: install jenv
  command: |
    bash -lc 'anyenv install jenv'
  when: which_jenv.rc > 0

- name: clear init script cache
  file:
    dest: '{{ item }}'
    state: absent
  with_fileglob:
    - '{{ anyenv.dir }}/init.*'

- name: enable export plugin
  command: |
    bash -lc 'jenv enable-plugin export'

# @see https://github.com/jenv/jenv/pull/200
- name: apply patch to export plugin
  patch:
    src: export_jenv_hook.zsh.patch
    dest: '{{ anyenv.envs_dir }}/jenv/plugins/export/etc/jenv.d/init/export_jenv_hook.zsh'

- name: register java home
  command: |
    bash -lc 'jenv add "$(/usr/libexec/java_home)"'
