# @see https://github.com/jwilm/alacritty/blob/master/alacritty.yml

window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 6
    y: 6

  dynamic_padding: false
  decorations: full
  startup_mode: Maximized

font:
  size: 12.0
  use_thin_strokes: true

  offset:
    x: 0
    y: 2

  glyph_offset:
    x: 0
    y: 1

colors:
  primary:
    background: '0x1a1a1a' # candle-theme: background
    foreground: '0xa8a8a8' # candle-theme: foreground

  normal:
    black:   '0x444444' # candle-theme: selection
    red:     '0xaf7070' # candle-theme: red
    green:   '0xa3a46f' # candle-theme: green
    yellow:  '0xceb481' # candle-theme: yellow
    blue:    '0x8397a9' # candle-theme: blue
    magenta: '0x9d91a9' # candle-theme: purple
    cyan:    '0x8aaaa5' # candle-theme: aqua
    white:   '0x626262' # candle-theme: comment

  bright:
    black:   '0x444444' # candle-theme: selection
    red:     '0xaf7070' # candle-theme: red
    green:   '0xa3a46f' # candle-theme: green
    yellow:  '0xceb481' # candle-theme: yellow
    blue:    '0x8397a9' # candle-theme: blue
    magenta: '0x9d91a9' # candle-theme: purple
    cyan:    '0x8aaaa5' # candle-theme: aqua
    white:   '0x626262' # candle-theme: comment

  dim:
    black:   '0x444444' # candle-theme: selection
    red:     '0x503131' # candle-theme: dark_red
    green:   '0x4c4b30' # candle-theme: dark_green
    yellow:  '0x5f5138' # candle-theme: dark_yellow
    blue:    '0x39444d' # candle-theme: dark_blue
    magenta: '0x47404d' # candle-theme: dark_purple
    cyan:    '0x3c4e4b' # candle-theme: dark_aqua
    white:   '0x626262' # candle-theme: comment

mouse:
  hide_when_typing: true

shell:
  program: /usr/local/bin/tmux
  args:
    - -l
    - -u # @see https://github.com/tmux/tmux/issues/328

key_bindings:
  - { key: Q, mods: Control, chars: "\x11" } # @see https://github.com/jwilm/alacritty/issues/1359
  - { key: N, mods: Command, command: { program: "open", args: ["-n", "/Applications/Alacritty.app"] } }
