[Editor]
StartFullscreen = false
BorderlessWindow = false

FontFamily = "Fira Code"
FontSize = 12
Linespace = 2

ExtCmdline   = false
ExtPopupmenu = true
ExtTabline   = false
ExtMessages  = false

IndentGuide = true

# DrawWindowSeparator = true
# DrawBorderForFloatWindow = true
# WindowSeparatorColor = "#000"
# WindowSeparatorTheme = "dark"

# ginitvim = '''
#   augroup GonvimAu
#     autocmd!
#   augroup end
#   augroup GonvimAuStatusline
#     autocmd!
#   augroup end
#   augroup GonvimAuLint
#     autocmd!
#   augroup end
#   augroup GonvimAuMd
#     autocmd!
#   augroup end
#   augroup GonvimAuFilePath
#     autocmd!
#   augroup end
#   augroup GonvimAuMinimap
#     autocmd!
#   augroup end
#   augroup GonvimAuScrollbar
#     autocmd!
#   augroup end
# '''

[MiniMap]
Disable = true
