- name: create directory
  file:
    dest:  '{{ home_path }}/Library/Application Support/Karabiner'
    state: directory

- name: copy private.xml
  copy:
    src:  private.xml
    dest: '{{ home_path }}/Library/Application Support/Karabiner'
