- set_fact:
    swift: {}

- block:
    - name: create tmp directory
      command: mktemp -d
      register: mktemp

    - name: download swiftlint
      get_url:
        url:  'https://github.com/realm/SwiftLint/releases/download/{{ swift.swiftlint_version }}/SwiftLint.pkg'
        dest: '{{ mktemp.stdout }}/SwiftLint.pkg'

    - name: install swiftlint
      shell: |
        installer -pkg SwiftLint.pkg -target /
      become: True
      args:
        chdir: '{{ mktemp.stdout }}'

  always:
    - name: delete tmp directory
      file:
        dest:  '{{ mktemp.stdout }}'
        state: absent

  when: swift.swiftlint_version
