- name: check pyenv
  command: |
    which pyenv
  register: which_pyenv
  ignore_errors: True

- name: install pyenv
  command: |
    anyenv install pyenv
  when: which_pyenv.rc > 0

- name: get installed versions
  command: |
    pyenv versions
  register: installed_versions

- name: install python
  command: |
    pyenv install '{{ item }}'
  when: |
    python_versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ python_versions }}'

- name: set global python
  command: |
    pyenv global '{{ python_versions[0] }}'
  when: python_versions

- name: install packages
  pip:
    name:               '{{ item.name | default(item) }}'
    extra_args:         '{{ item.extra_args | default("") }}'
    state:              latest
    virtualenv_command: pyenv
  become: True
  with_items: '{{ packages }}'
  when: packages
