#!/bin/bash

cd ~/dotfiles


#  Homebrew
#-----------------------------------------------
which brew > /dev/null 2>&1
if [ $? -ne 0 ]; then
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
fi

sh ./Brewfile


#  rbenv
#-----------------------------------------------
rbenv install 2.1.1
rbenv global 2.1.1


#  Gem
#-----------------------------------------------
rbenv exec gem install bundler
bundle


#  Node packages
#-----------------------------------------------
npm i -g


#  Vagrant
#-----------------------------------------------
# vagrant box add centos64-6.5.3 https://github.com/2creatives/vagrant-centos/releases/download/v6.5.3/centos65-x86_64-20140116.box
# vagrant plugin install sahara


#  R
#-----------------------------------------------
r -f packages.r


#  Haskell
#-----------------------------------------------
cabal update
cabal install cabal-install
cabal install erd
