#!/bin/bash

echo "Creating symbolic links..."
cd ~

for file in ~/dotfiles/_*; do
  f=$(basename $file)
  f="$HOME/${f/_/.}"

  if [ ! -L "$f" ]; then
    ln -sf "$file" "$f"
    echo "Link: $file --> $f"
  fi
done

echo "ok"
