for file in ~/dotfiles/_zsh/{exports,aliases,functions,prompt,secrets}.zsh; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

eval "$(rbenv init -)"
eval "$(gh alias -s)"
source ~/.nvm/nvm.sh
