[ -f ~/.profile ] && source ~/.profile

#  Load
#-----------------------------------------------
for file in ~/.zsh/src/{aliases}.zsh; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file
