- name: install dein.vim
  git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/vim/dein/repos/github.com/Shougo/dein.vim'
    update: False

- name: install dependency
  homebrew:
    name:  '{{ item }}'
    state: present
  with_items:
    - lua

- name: install vim
  homebrew:
    name:            vim
    state:           present
    install_options: '--without-nls --with-override-system-vi --with-lua --with-python3'

- name: install macvim
  homebrew:
    name:            macvim
    state:           present
    install_options: '--with-lua --with-python3 --HEAD'

- name: link macvim
  file:
    src:   /usr/local/opt/macvim/MacVim.app
    dest:  /Applications/MacVim.app
    state: link
    force: yes
