- name: install dein.vim
  git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/nvim/dein/repos/github.com/Shougo/dein.vim'
    update: False

- name: install python3
  homebrew:
    name:  python3
    state: latest

- name: install latest pip
  pip:
    name: pip
    executable: pip3
    state: latest

- name: install python libraries
  pip:
    name:  '{{ item }}'
    state: latest
  with_items:
    - neovim
    - vim-vint
    - pynvim

- name: install deno
  homebrew:
    name:  deno
    state: latest

- name: install neovim
  homebrew:
    name:  neovim
    state: latest

#  coc.nvim
#-----------------------------------------------
- name: coc.nvim | install deps via brew
  homebrew:
    name:  '{{ item }}'
    state: latest
  with_items:
    - ansible-lint
    - clang-format
    - llvm # clangd
    - shellcheck
    - watchman

- name: coc.nvim | install deps via pip3
  pip:
    name:  '{{ item }}'
    state: latest
  with_items:
    - python-language-server
