- name: install neovim
  homebrew:
    name:  neovim
    state: latest

- name: install python libraries
  pip:
    executable: pip3
    name:       '{{ item }}'
    state:      latest
  with_items:
    - neovim

- name: install dein.vim
  git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/nvim/dein/repos/github.com/Shougo/dein.vim'
    update: False

- name: install deps via brew
  homebrew:
    name:  '{{ item }}'
    state: latest
  with_items:
    - ansible-lint
    - clang-format
    - deno
    - llvm # clangd
    - shellcheck
    - watchman

- name: install deps via pip3
  pip:
    executable: pip3
    name:       '{{ item }}'
    state:      latest
  with_items:
    - pynvim
    - python-language-server
    - vim-vint
