- name: install dein.vim
  git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/vim/dein/repos/github.com/Shougo/dein.vim'
    update: False

- name: install python3
  homebrew:
    name:  python3
    state: present

- name: install neovim python lib
  pip3:
    executable: pip3
    name:       neovim
    state:      latest
  become: yes

- name: install macvim
  homebrew:
    name:            macvim
    state:           present
    install_options: '--HEAD --with-python3 --override-system-vim'

# - name: link macvim
#   file:
#     src:   /usr/local/opt/macvim/MacVim.app
#     dest:  /Applications/MacVim.app
#     state: link
#     force: yes
#
# - name: link vim binary
#   file:
#     src:   /usr/local/opt/macvim/MacVim.app/Contents/bin/vim
#     dest:  /usr/local/bin/vim
#     state: link
#     force: yes
