- name: install neovim
  community.general.homebrew:
    name:  neovim
    state: latest

- name: install dein.vim
  ansible.builtin.git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/nvim/dein/repos/github.com/Shougo/dein.vim'
    update: false

- name: install deps via brew
  community.general.homebrew:
    name:
      - ansible-lint
      - clang-format
      - deno
      - terraform-ls
      - llvm # clangd
      - shellcheck
      - watchman
    state: latest

#- name: install deps via pip
#  pip:
#    name:  '{{ item }}'
#    state: latest
#  with_items:
#    - pynvim
#    - python-language-server
#    - vim-vint
