- name: install dein.vim
  git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/nvim/dein/repos/github.com/Shougo/dein.vim'
    update: False

- name: install python3
  homebrew:
    name:  python3
    state: present

- name: install python libraries
  pip:
    executable: pip3
    name:       '{{ item }}'
    state:      latest
  with_items:
    - neovim
    - vim-vint
    - pynvim

- name: install deno
  homebrew:
    name:  deno
    state: present

- name: install neovim
  homebrew:
    name:  neovim
    state: present

#  coc.nvim
#-----------------------------------------------
- name: coc.nvim | install deps via brew
  homebrew:
    name:  '{{ item }}'
    state: present
  with_items:
    - watchman
    - llvm # (clangd, clang-format)
    - shellcheck

- name: coc.nvim | install deps via pip3
  pip:
    executable: pip3
    name:       '{{ item }}'
    state:      present
  with_items:
    - python-language-server
