- name: install dein.vim
  git:
    repo:   https://github.com/Shougo/dein.vim
    dest:   '{{ dotfiles_path }}/vim/dein/repos/github.com/Shougo/dein.vim'
    update: False

- name: install python3
  homebrew:
    name:  python3
    state: present

- name: install python libraries
  pip:
    executable: pip3
    name:       '{{ item }}'
    state:      latest
  with_items:
    - neovim
    - vim-vint
    - pynvim

- name: install neovim
  homebrew:
    name:  neovim
    state: present
