- set_fact:
    vscode: {}
    vscode_path: '{{ home_path }}/Library/Application Support/Code/User'

- name: install vscode
  homebrew_cask:
    name:  visual-studio-code
    state: latest
    sudo_password: '{{ ansible_become_pass }}'

- block:
    - name: allocate parent directories
      file:
        dest:    '{{ vscode_path }}/{{ item }}'
        state:   directory
        recurse: yes
      loop_control:
        label: '{{ vscode_path }}/{{ item }}'
      with_items: '{{ vscode.link.values() | map("dirname") | unique | list }}'

    - name: check destinations
      stat:
        path: '{{ vscode_path }}/{{ item.value }}'
      loop_control:
        label: '{{ item.value }}'
      with_dict: '{{ vscode.link }}'
      register: dest_stat

    - name: create backup files
      command: |
        mv -f \
          {{ vscode_path | quote }}/{{ item.item.value | quote }} \
          {{ vscode_path | quote }}/{{ item.item.value | quote }}.bak
      when: item.stat.exists and not item.stat.islnk
      loop_control:
        label: '{{ item.item.value }}'
      with_items: '{{ dest_stat.results }}'

    - name: create symlinks
      file:
        src:   '{{ dotfiles_path }}/{{ item.key }}'
        dest:  '{{ vscode_path }}/{{ item.value }}'
        state: link
        force: yes
      loop_control:
        label: '{{ item.value }}'
      with_dict: '{{ vscode.link }}'

  when: vscode.link

- name: get installed extensions
  command: |
    bash -lc 'code --list-extensions'
  register: installed_vscode_exts

# code --list-extensions | sed -e 's/^/- /g' | pbcopy
- name: install extensions
  command: |
    bash -lc 'code --install-extension {{ item | quote }}'
  when: |
    installed_vscode_exts.stdout.find(item) == -1
  with_items:
    - TabNine.tabnine-vscode
    - Tyriar.sort-lines
    - alygin.vscode-tlaplus
    - apollographql.vscode-apollo
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - creasty.vscode-altr
    - creasty.vscode-pattern-switch
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - eg2.vscode-npm-script
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - jock.svg
    - ms-vsliveshare.vsliveshare
    - pflannery.vscode-versionlens
    - sleistner.vscode-fileutils
    - steoates.autoimport
    - streetsidesoftware.code-spell-checker
    - styled-components.vscode-styled-components
    - swindh.enumerator
    - vincaslt.highlight-matching-tag
    - wayou.vscode-todo-highlight
    - wmaurer.change-case
    - wwm.better-align
