- name: create directories
  ansible.builtin.file:
    dest:  '{{ home_path }}/{{ item }}'
    mode:  '0700'
    state: directory
  loop:
    - '.ssh'
    - '.ssh/config.d'
    - '.ssh/keys'

- name: copy common config
  ansible.builtin.copy:
    src:  '{{ item }}'
    dest: '{{ home_path }}/.ssh/config.d/'
    mode: '0600'
  loop: '{{ query("fileglob", "_*") }}'

- name: assemble config.d
  ansible.builtin.assemble:
    src:           '{{ home_path }}/.ssh/config.d'
    dest:          '{{ home_path }}/.ssh/config'
    mode:          '0600'
    ignore_hidden: true
    delimiter:     "\n"
