- name: create .ssh
  file:
    dest:  '{{ home_path }}/.ssh'
    mode:  0700
    state: directory

- name: create config
  file:
    dest: '{{ home_path }}/.ssh/config'
    mode: 0600

- name: create config.d
  file:
    dest:  '{{ home_path }}/.ssh/config.d'
    mode:  0700
    state: directory

- name: copy common config
  copy:
    src:  '{{ item }}'
    dest: '{{ home_path }}/.ssh/config.d/'
    mode: 0600
  with_fileglob:
    - '_*'

- name: merge configs
  shell: |
    cat {{ home_path | quote }}/.ssh/config.d/* > {{ home_path | quote }}/.ssh/config
