- name: create directories
  file:
    dest:  '{{ home_path }}/.ssh'
    mode:  0700
    state: directory
  with_items:
    - '.ssh'
    - '.ssh/config.d'
    - '.ssh/keys'

- name: create config
  file:
    dest: '{{ home_path }}/.ssh/config'
    mode: 0600

- name: copy common config
  copy:
    src:  '{{ item }}'
    dest: '{{ home_path }}/.ssh/config.d/'
    mode: 0600
  with_fileglob:
    - '_*'

- name: merge configs
  shell: |
    cat {{ home_path | quote }}/.ssh/config.d/* > {{ home_path | quote }}/.ssh/config
