applications:
  - adobe-creative-cloud
  - alfred
  - android-studio
  - boot2docker # docker-toolbox? docker for mac?
  - dropbox
  - firefox
  - flip4mac
  - flux
  - google-chrome
  - google-hangouts
  - google-japanese-ime
  - growlnotify
  - iterm2
  - karabiner
  - ngrok
  - qlcolorcode
  - qlmarkdown
  - qlstephen
  - quicklook-json
  - sequel-pro
  - skype
  - vagrant
  - virtualbox
  - webpquicklook
  - xquartz

repositories:
  - creasty/homebrew-creasty
  - homebrew/boneyard
  - homebrew/dupes
  - homebrew/science
  - josegonzalez/php
  - supermomonga/homebrew-splhack

packages:
  - android-sdk
  - argon/mas/mas
  - { name: 'awscli', state: 'head' }
  - batik
  - binutils
  - cabal-install
  - chisel
  - clib
  - clisp
  - cloc
  - ctags
  - { name: 'ctags-objc-ja', state: 'head', install_options: '--enable-japanese-support' }
  - { name: 'curl', install_options: '--with-ssl --with-libssh2' }
  - direnv
  - elixir
  - eot-utils
  - fontconfig
  - fontforge
  - freetype
  - fswatch
  - gcutil
  - gdb
  - gdbm
  - gettext
  - ghc
  - ghostscript
  - git
  - git-lfs
  - gpg
  - graphviz
  - envchain
  - imagemagick
  - jbig2dec
  - jo
  - jpeg
  - jq
  - libepoxy
  - libiconv
  - libpcap
  - libxml2
  - libxslt
  - lua
  - luajit
  - luarocks
  - { name: 'macvim', state: 'head', install_options: '--with-luajit' }
  - memcached
  - mercurial
  - mongodb
  - mysql
  - ngrep
  - nkf
  - opencv
  - optipng
  - osquery
  - parallel
  - pcre
  - phantomjs
  - php55
  - plantuml
  - postgresql
  - pstree
  - python3
  - q
  - r  # require xquartz to be installed
  - ranger
  - redis
  - rsense
  - ruby-build
  - sbt
  - scala
  - sqlite
  - terraform
  - the_silver_searcher
  - tig
  - tmux
  - tree
  - typesafe-activator
  - { name: 'vim', state: 'head', install_options: '--disable-nls --override-system-vi --with-luajit' }
  - w3m
  - webkit2png
  - { name: 'wget', install_options: '--enable-iri' }
  - xctool
  - zsh
