- name: create tmp directory
  command: mktemp -d
  register: mktemp

- block:
    - name: download otp
      get_url:
        url:  'http://www.erlang.org/download/otp_src_{{ version }}.tar.gz'
        dest: '{{ mktemp.stdout }}/otp_src_{{ version }}.tar.gz'

    - name: unarchive otp
      shell: |
        if ! [ -d './otp_src_{{ version }}' ]; then
          tar xzf '{{ mktemp.stdout }}/otp_src_{{ version }}.tar.gz'
        fi
      args:
        chdir: '{{ mktemp.stdout }}'

    - name: make otp
      shell: |
        ./configure \
          --prefix={{ erlang.releases_dir | quote }}/{{ version }} \
          --enable-dynamic-ssl-lib \
          --with-ssl=/usr/local/opt/openssl \
        && make \
        && make install
      args:
        chdir: '{{ mktemp.stdout }}/otp_src_{{ version }}'

  always:
    - name: delete tmp directory
      file:
        dest:  '{{ mktemp.stdout }}'
        state: absent
