- set_fact:
    erlang: {}

- name: install deps
  homebrew:
    name:  '{{ item }}'
    state: present
  with_items:
    - fop
    - openssl
    - unixodbc
    - wxmac

- name: check erlenv
  command: |
    bash -ic 'which erlenv'
  register: which_erlenv
  ignore_errors: yes

- name: install erlenv
  command: |
    bash -ic 'anyenv install erlenv'
  when: which_erlenv.rc > 0

- name: get installed versions
  command: |
    bash -ic 'erlenv releases'
  register: installed_versions

- include: install.yml
  vars:
    version: '{{ item }}'
  when: |
    erlang.versions and erlang.releases_dir and installed_versions.stdout.find(item) == -1
  with_items: '{{ erlang.versions }}'

- name: set global erlang
  command: |
    bash -ic 'erlenv global {{ erlang.versions[0] | quote}}'
  when: erlang.versions

- name: rehash
  command: |
    bash -ic 'erlenv rehash'
