homebrew:
  # brew list --cask --full-name
  applications:
    - 1password                   # https://1password.com/
    - 1password/tap/1password-cli # https://developer.1password.com/docs/cli
    - adobe-creative-cloud        # https://creative.adobe.com/products/creative-cloud
    - alacritty                   # https://github.com/jwilm/alacritty
    - appcleaner                  # https://freemacsoft.net/appcleaner/
    - chromedriver                # https://sites.google.com/a/chromium.org/chromedriver/home
    - creasty/tools/keyboard      # https://github.com/creasty/Keyboard
    - docker                      # https://www.docker.com/community-edition
    - figma                       # https://www.figma.com/
    - google-chat                 # https://gsuite.google.com/products/chat/
    - google-chrome               # https://www.google.com/chrome/
    - google-cloud-sdk            # https://cloud.google.com/sdk/
    - google-drive                # https://www.google.com/drive/
    - google-japanese-ime         # https://www.google.co.jp/ime/
    - imageoptim                  # https://imageoptim.com/mac
    - istat-menus                 # https://bjango.com/mac/istatmenus/
    - kitty                       # https://github.com/kovidgoyal/kitty
    - ngrok                       # https://ngrok.com/
    - notion                      # https://www.notion.so/
    - pushplaylabs-sidekick       # https://www.meetsidekick.com/
    - qlcolorcode                 # https://github.com/anthonygelibert/QLColorCode
    - qlmarkdown                  # https://github.com/toland/qlmarkdown
    - qlstephen                   # https://whomwah.github.io/qlstephen/
    - quicklook-json              # http://www.sagtau.com/quicklookjson.html
    - raycast                     # https://raycast.app/
    - rightfont                   # https://rightfontapp.com/
    - spotify                     # https://www.spotify.com/
    - tableplus                   # https://tableplus.io/
    - tunnelbear                  # https://www.tunnelbear.com/
    - webpquicklook               # https://github.com/emin/WebPQuickLook

  # brew leaves | xargs brew desc --eval-all | sed -E 's/^([^:]*): /- \1 # /g'
  packages:
    - awscli              # Official Amazon AWS command-line interface
    - bat                 # Clone of cat(1) with syntax highlighting and Git integration
    - circleci            # Enables you to reproduce the CircleCI environment locally
    - cloc                # Statistics utility to count lines of code
    - cmake               # Cross-platform make
    - creasty/tools/rid   # Run commands in container as if were native
    - ctags               # Reimplementation of ctags(1)
    - curl                # Get a file from an HTTP, HTTPS or FTP server
    - deno                # Secure runtime for JavaScript and TypeScript
    - diff-so-fancy       # Good-lookin' diffs with diff-highlight and more
    - direnv              # Load/unload environment variables based on $PWD
    - envchain            # Secure your credentials in environment variables
    - exa                 # Modern replacement for 'ls'
    - expect              # Program that can automate interactive applications
    - fd                  # Simple, fast and user-friendly alternative to find
    - ffmpeg              # Play, record, convert, and stream audio and video
    - gh                  # GitHub command-line tool
    - ghq                 # Remote repository management made easy
    - git                 # Distributed revision control system
    - git-filter-repo     # Quickly rewrite git repository history
    - git-lfs             # Git extension for versioning large files
    - gnupg               # GNU Pretty Good Privacy (PGP) package
    - graphviz            # Graph visualization software from AT&T and Bell Labs
    - hyperfine           # Command-line benchmarking tool
    - imagemagick         # Tools and libraries to manipulate images in many formats
    - jo                  # JSON output from a shell
    - jq                  # Lightweight and flexible command-line JSON processor
    - ktr0731/evans/evans # Evans: more expressive universal gRPC client
    - libiconv            # Conversion library
    - libpq               # Postgres C API library
    - massren             # Easily rename multiple files using your text editor
    - ngrep               # Network grep
    - nkf                 # Network Kanji code conversion Filter (NKF)
    - parallel            # Shell command parallelization utility
    - pastel              # Command-line tool to generate, analyze, convert and manipulate colors
    - peco                # Simplistic interactive filtering tool
    - procs               # Modern replacement for ps written by Rust
    - protobuf            # Protocol buffers (Google's data interchange format)
    - ripgrep             # Search tool like grep and The Silver Searcher
    - sd                  # Intuitive find & replace CLI
    - terraform           # Tool to build, change, and version infrastructure
    - tmux                # Terminal multiplexer
    - trash               # CLI tool that moves files or folder to the trash
    - webp                # Image format providing lossless and lossy compression for web images
    - xh                  # Friendly and fast tool for sending HTTP requests

# [TO BE DELETED] No longer works on latest macOS.
# https://github.com/mas-cli/mas#%EF%B8%8F-known-issues
mas:
  # List installed apps by
  #
  #   $ mas list
  #
  applications:
    - '1066302071' # New File Menu Free
    - '1091189122' # Bear
    - '425424353'  # The Unarchiver
    - '497799835'  # Xcode
    - '904280696'  # Things
    - '975937182'  # Fantastical

launchagent:
  plist_dir: '{{ dotfiles_path }}/config/launchagent'

link:
  # XDG config directory
  config/alacritty: .config/alacritty
  config/bat:       .config/bat
  config/git:       .config/git
  config/kitty:     .config/kitty
  config/peco:      .config/peco
  config/ripgreprc: .config/.ripgreprc
  config/tmux:      .config/tmux

  # Home directory
  home/ansible.cfg:   .ansible.cfg
  home/aws/config:    .aws/config
  home/bundle/config: .bundle/config
  home/cargo/config:  .cargo/config
  home/ctags:         .ctags
  home/curlrc:        .curlrc
  home/fdignore:      .fdignore
  home/gemrc:         .gemrc
  home/irbrc:         .irbrc
  home/pgclirc:       .pgclirc
  home/pryrc:         .pryrc
  home/railsrc:       .railsrc
  home/rgignore:      .rgignore
  home/rspec:         .rspec
  home/rubocop.yml:   .rubocop.yml

  # Special
  nvim:                    .config/nvim
  shell/bash/bash_profile: .bash_profile
  shell/bash/bashrc:       .bashrc
  shell/profile:           .profile
  shell/zsh/zshenv:        .zshenv
  shell/zsh/zshrc:         .zshrc
  shell/zsh:               .zsh

anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'
  libexec_dir: '{{ home_path }}/.anyenv/libexec'

golang:
  tools:
    - golangci/tap/golangci-lint # Fast linters runner for Go
    - gopls                      # Language server for the Go language

nodejs:
  default_packages_path: '{{ dotfiles_path }}/config/nodenv/default-packages'

  # https://nodejs.org/en
  versions:
    - '18.15.0'

  plugins:
    - nodenv/nodenv-default-packages

ruby:
  default_gems_path: '{{ dotfiles_path }}/config/rbenv/default-gems'

  # https://www.ruby-lang.org/en/downloads/
  versions:
    - '3.2.1'

  plugins:
    - ianheggie/rbenv-binstubs # A Bundler binstubs Plugin for rbenv
    - rbenv/rbenv-default-gems # Automatically install gems every time you install a new version of Ruby

rust:
  components:
    - clippy        # https://github.com/rust-lang/rust-clippy
    - rls           # https://github.com/rust-lang/rls
    - rust-analysis # https://github.com/rust-lang/rls
    - rust-src      # https://github.com/rust-lang/rust

vagrant:
  boxes: {}

  plugins:
    - dotenv        # https://github.com/johnbellone/vagrant-dotenv ?
    - sahara        # https://github.com/jedi4ever/sahara
    - vagrant-share # https://www.vagrantup.com/docs/share/

vscode:
  link:
    config/vscode/keybindings.json: keybindings.json
    config/vscode/settings.json: settings.json

  # code --list-extensions | sed -e 's/^/- /g' | pbcopy
  extensions:
    - TabNine.tabnine-vscode
    - Tyriar.sort-lines
    - alygin.vscode-tlaplus
    - apollographql.vscode-apollo
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - creasty.vscode-altr
    - creasty.vscode-pattern-switch
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - eg2.vscode-npm-script
    - esbenp.prettier-vscode
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - jock.svg
    - ms-vsliveshare.vsliveshare
    - pflannery.vscode-versionlens
    - sleistner.vscode-fileutils
    - steoates.autoimport
    - streetsidesoftware.code-spell-checker
    - styled-components.vscode-styled-components
    - swindh.enumerator
    - vincaslt.highlight-matching-tag
    - wayou.vscode-todo-highlight
    - wmaurer.change-case
    - wwm.better-align
