homebrew:
  repositories:
    - creasty/tools
    - dtan4/tools

  applications:
    - adobe-creative-cloud # https://creative.adobe.com/products/creative-cloud
    - alfred               # https://www.alfredapp.com/
    #- android-sdk          # https://developer.android.com/index.html
    #- android-studio       # https://developer.android.com/studio/index.html
    - appcleaner           # https://freemacsoft.net/appcleaner/
    - docker               # https://www.docker.com/community-edition
    - dropbox              # https://www.dropbox.com/
    - google-chrome        # https://www.google.com/chrome/
    - google-hangouts      # https://www.google.com/tools/dlpage/hangoutplugin
    - google-japanese-ime  # https://www.google.co.jp/ime/
    - imageoptim           # https://imageoptim.com/mac
    #- istat-menus          # https://bjango.com/mac/istatmenus/
    - iterm2               # https://www.iterm2.com/
    - jetbrains-toolbox    # https://www.jetbrains.com/toolbox/app/
    - keyboard             # https://github.com/creasty/Keyboard
    - ngrok                # https://ngrok.com/
    - qlcolorcode          # https://github.com/anthonygelibert/QLColorCode
    - qlmarkdown           # https://github.com/toland/qlmarkdown
    - qlstephen            # https://whomwah.github.io/qlstephen/
    - quicklook-json       # http://www.sagtau.com/quicklookjson.html
    - sequel-pro           # https://www.sequelpro.com/
    - skype                # https://www.skype.com/
    - transmit             # https://panic.com/transmit/
    - tunnelbear           # https://www.tunnelbear.com/
    - vagrant              # https://www.vagrantup.com/
    #- virtualbox           # https://www.virtualbox.org/
    - visual-studio-code   # https://code.visualstudio.com/
    - webpquicklook        # https://github.com/dchest/webp-quicklook
    - wwdc                 # https://wwdc.io/

  # Comments are generated by:
  #
  #   $ for name in `pbpaste`; do echo "$name # $(brew info $name | sed -n '2p')"; done
  #
  packages:
    - argon/mas/mas        # Mac App Store command-line interface
    - binutils             # FSF Binutils for native development
    - carthage             # Decentralized dependency manager for Cocoa
    - clib                 # Package manager for C programming
    - cloc                 # Statistics utility to count lines of code
    - creasty/tools/rid    # Run commands in container as if were native
    - ctags                # Reimplementation of ctags(1)
    - direnv               # Load/unload environment variables based on $PWD
    - dtan4/tools/k8sec    # CLI tool to manage Kubernetes Secrets easily
    - envchain             # Secure your credentials in environment variables
    - eot-utils            # Tools to convert fonts from OTF/TTF to EOT format
    - fontconfig           # XML-based font configuration API for X Windows
    - fontforge            # Command-line outline and bitmap font editor/converter
    - freetype             # Software library to render fonts
    - fswatch              # Monitor a directory for changes and run a shell command
    - gdb                  # GNU debugger
    - gdbm                 # GNU database manager
    - gettext              # GNU internationalization (i18n) and localization (l10n) library
    - ghostscript          # Interpreter for PostScript and PDF
    - git                  # Distributed revision control system
    - git-lfs              # Git extension for versioning large files
    - gpg                  # GNU Privacy Guard: a free PGP replacement
    - heroku/brew/heroku   # Everything you need to get started with Heroku
    - imagemagick          # Tools and libraries to manipulate images in many formats
    - jbig2dec             # JBIG2 decoder and library (for monochrome documents)
    - jo                   # JSON output from a shell
    - jpeg                 # Image manipulation library
    - jq                   # Lightweight and flexible command-line JSON processor
    - libepoxy             # Library for handling OpenGL function pointer management
    - libiconv             # Conversion library
    - libpcap              # Portable library for network traffic capture
    - libxml2              # GNOME XML library
    - libxslt              # C XSLT library for GNOME
    - massren              # Easily rename multiple files using your text editor
    - ngrep                # Network grep
    - nkf                  # Network Kanji code conversion Filter (NKF)
    - parallel             # GNU parallel shell command
    - pcre                 # Perl compatible regular expressions library
    - protobuf             # Protocol buffers (Google's data interchange format)
    - python               # Interpreted, interactive, object-oriented programming language
    - screenresolution     # Get, set, and list display resolution
    - the_silver_searcher  # Code-search similar to ack
    - tmux                 # Terminal multiplexer
    - tree                 # Display directories as trees (with optional color/HTML output)
    - webp                 # Image format providing lossless and lossy compression for web images
    - xctool               # Drop-in replacement for xcodebuild with a few extra features
    - yarn                 # JavaScript package manager
    - expect               # Program that can automate interactive applications

mas:
  appstore_id:       '{{ appstore_id }}'
  appstore_password: '{{ appstore_password }}'

  # List installed apps by
  #
  #   $ mas list
  #
  applications:
    - '1031280567' # Postico
    - '1091189122' # Bear
    - '1333542190' # 1Password 7
    - '425424354'  # The Unarchiver
    - '497799835'  # Xcode
    - '540348655'  # Monosnap
    - '803453959'  # Slack
    - '904280696'  # Things3
    - '928494006'  # PopHub
    - '975937182'  # Fantastical 2

launchagent:
  plist_dir: '{{ dotfiles_path }}/config/launchagent'

link:
  bash/bash_profile:         .bash_profile
  bash/bashrc:               .bashrc
  config/agignore:           .agignore
  config/ansible.cfg:        .ansible.cfg
  config/aws/config:         .aws/config
  config/ctags:              .ctags
  config/curlrc:             .curlrc
  config/gocode/config.json: .config/gocode/config.json
  config/peco:               .peco
  config/pgclirc:            .pgclirc
  git/gitconfig:             .gitconfig
  git/gitignore:             .gitignore
  ruby/bundle/config:        .bundle/config
  ruby/gemrc:                .gemrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  ruby/railsrc:              .railsrc
  ruby/rbenv/default-gems:   .anyenv/envs/rbenv/default-gems
  ruby/rspec:                .rspec
  ruby/rubocop.yml:          .rubocop.yml
  tmux/tmux.conf:            .tmux.conf
  tmux:                      .tmux
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .vim
  zsh/zshenv:                .zshenv
  zsh/zshrc:                 .zshrc
  zsh:                       .zsh

anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

golang:
  packages:
    # tools
    - github.com/motemen/ghq        # Remote repository management made easy
    - github.com/peco/peco/cmd/peco # Simplistic interactive filtering tool
    - github.com/rakyll/hey         # HTTP load generator, ApacheBench (ab) replacement

    # dev tools
    - github.com/golang/dep/cmd/dep # Go dependency management tool
    - golang.org/x/lint/golint      # Golint is a linter for Go source code
    - github.com/nsf/gocode         # An autocompletion daemon for the Go programming language
    - github.com/rogpeppe/godef     # find symbol information in Go source

nodejs:
  versions:
    - '8.11.3'

  packages:
    - coffee-script

ruby:
  versions:
    - '2.5.1'

  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'

  plugins:
    - ianheggie/rbenv-binstubs # A Bundler binstubs Plugin for rbenv
    - rbenv/rbenv-default-gems # Automatically install gems every time you install a new version of Ruby

vagrant:
  boxes: {}

  plugins:
    - sahara        # https://github.com/jedi4ever/sahara
    - dotenv        # https://github.com/johnbellone/vagrant-dotenv ?
    - vagrant-share # https://www.vagrantup.com/docs/share/
