anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

golang:
  versions:
    - '1.7.1'

  packages:
    - github.com/Masterminds/glide
    - github.com/golang/lint/golint
    - github.com/laurent22/massren
    - github.com/motemen/ghq
    - github.com/nsf/gocode
    - github.com/peco/peco/cmd/peco
    - github.com/rakyll/boom

homebrew:
  repositories:
    - creasty/tools
    - homebrew/boneyard
    - homebrew/dupes
    - homebrew/science

  applications:
    - adobe-creative-cloud
    - alfred
    # - android-sdk
    # - android-studio
    - keyboard
    - docker
    - dropbox
    - google-chrome
    - google-hangouts
    - google-japanese-ime
    - imageoptim
    - istat-menus
    - iterm2
    - jetbrains-toolbox
    - ngrok
    - qlcolorcode
    - qlmarkdown
    - qlstephen
    - quicklook-json
    - sequel-pro
    - skype
    - vagrant
    - virtualbox
    - webpquicklook

  # Comments are generated by:
  #
  #   $ for name in `pbpaste`; do echo "$name # $(brew info $name | sed -n '2p')"; done
  #
  packages:
    - argon/mas/mas       # Mac App Store command-line interface
    - binutils            # FSF Binutils for native development
    - carthage            # Decentralized dependency manager for Cocoa
    - clib                # Package manager for C programming
    - cloc                # Statistics utility to count lines of code
    - creasty/tools/rid   # Run commands in container as if were native
    - ctags               # Reimplementation of ctags(1)
    - direnv              # Load/unload environment variables based on $PWD
    - dtan4/tools/k8sec   # CLI tool to manage Kubernetes Secrets easily
    - envchain            # Secure your credentials in environment variables
    - eot-utils           # Tools to convert fonts from OTF/TTF to EOT format
    - fontconfig          # XML-based font configuration API for X Windows
    - fontforge           # Command-line outline and bitmap font editor/converter
    - freetype            # Software library to render fonts
    - fswatch             # Monitor a directory for changes and run a shell command
    - gdb                 # GNU debugger
    - gdbm                # GNU database manager
    - gettext             # GNU internationalization (i18n) and localization (l10n) library
    - ghostscript         # Interpreter for PostScript and PDF
    - git                 # Distributed revision control system
    - git-lfs             # Git extension for versioning large files
    - gpg                 # GNU Privacy Guard: a free PGP replacement
    - heroku              # Everything you need to get started with Heroku
    - imagemagick         # Tools and libraries to manipulate images in many formats
    - jbig2dec            # JBIG2 decoder and library (for monochrome documents)
    - jo                  # JSON output from a shell
    - jpeg                # Image manipulation library
    - jq                  # Lightweight and flexible command-line JSON processor
    - libepoxy            # Library for handling OpenGL function pointer management
    - libiconv            # Conversion library
    - libpcap             # Portable library for network traffic capture
    - libxml2             # GNOME XML library
    - libxslt             # C XSLT library for GNOME
    - ngrep               # Network grep
    - nkf                 # Network Kanji code conversion Filter (NKF)
    - parallel            # GNU parallel shell command
    - pcre                # Perl compatible regular expressions library
    - screenresolution    # Get, set, and list display resolution
    - the_silver_searcher # Code-search similar to ack
    - tmux                # Terminal multiplexer
    - tree                # Display directories as trees (with optional color/HTML output)
    - webp                # Image format providing lossless and lossy compression for web images
    - xctool              # Drop-in replacement for xcodebuild with a few extra features
    - yarn                # JavaScript package manager

launchagent:
  plist_dir: '{{ dotfiles_path }}/app/launch_agent'

link:
  bash/bash_profile:                      .bash_profile
  bash/bashrc:                            .bashrc
  config/agignore:                        .agignore
  config/ansible.cfg:                     .ansible.cfg
  config/aws/config:                      .aws/config
  config/ctags:                           .ctags
  config/curlrc:                          .curlrc
  config/gocode/config.json:              .config/gocode/config.json
  config/peco:                            .peco
  config/pgclirc:                         .pgclirc
  dotssh:                                 .dotssh
  git/gitconfig:                          .gitconfig
  git/gitignore:                          .gitignore
  ruby/bundle/config:                     .bundle/config
  ruby/gemrc:                             .gemrc
  ruby/irbrc:                             .irbrc
  ruby/pryrc:                             .pryrc
  ruby/railsrc:                           .railsrc
  ruby/rbenv/default-gems:                .anyenv/envs/rbenv/default-gems
  ruby/rspec:                             .rspec
  tmux/tmux.conf:                         .tmux.conf
  tmux:                                   .tmux
  vim/gvimrc:                             .gvimrc
  vim/vimrc:                              .vimrc
  vim:                                    .vim
  zsh/zshenv:                             .zshenv
  zsh/zshrc:                              .zshrc
  zsh:                                    .zsh

mas:
  appstore_id:       '{{ secrets.mas.appstore_id }}'
  appstore_password: '{{ secrets.mas.appstore_password }}'

  # List installed apps by
  #
  #   $ mas list
  #
  applications:
    - '406056744'  # Evernote
    - '540348655'  # Monosnap
    - '425424354'  # The Unarchiver
    - '443987910'  # 1Password
    - '975937182'  # Fantastical 2
    - '497799835'  # Xcode
    - '412448059'  # ForkLift
    - '1031280567' # Postico
    - '803453959'  # Slack
    - '928494006'  # PopHub

nodejs:
  versions:
    - '7.2.1'

  packages:
    - coffee-script
    - speed-test

python:
  versions:
    - '3.5.0'

  packages:
    - vim-vint

ruby:
  versions:
    - '2.4.1'

  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'

  plugins:
    - ianheggie/rbenv-binstubs
    - sstephenson/rbenv-default-gems
    - sstephenson/rbenv-gem-rehash

swift:
  swiftlint_version: 0.13.2

vagrant:
  boxes: {}

  plugins:
    - sahara
    - dotenv
    - vagrant-share
