homebrew:
  repositories:
    - creasty/tools
    - dtan4/tools
    - heroku/brew
    - homebrew/cask-fonts

  applications:
    - adobe-creative-cloud     # https://creative.adobe.com/products/creative-cloud
    - alacritty                # https://github.com/jwilm/alacritty
    - alfred                   # https://www.alfredapp.com/
    - appcleaner               # https://freemacsoft.net/appcleaner/
    - chromedriver             # https://sites.google.com/a/chromium.org/chromedriver/home
    - creasty/tools/keyboard   # https://github.com/creasty/Keyboard
    - docker                   # https://www.docker.com/community-edition
    - figma                    # https://www.figma.com/
    - google-chrome            # https://www.google.com/chrome/
    - google-drive-file-stream # https://www.google.com/drive/
    - google-hangouts          # https://www.google.com/tools/dlpage/hangoutplugin
    - google-japanese-ime      # https://www.google.co.jp/ime/
    - imageoptim               # https://imageoptim.com/mac
    - istat-menus              # https://bjango.com/mac/istatmenus/
    - ngrok                    # https://ngrok.com/
    - notion                   # https://www.notion.so/
    - qlcolorcode              # https://github.com/anthonygelibert/QLColorCode
    - qlmarkdown               # https://github.com/toland/qlmarkdown
    - qlstephen                # https://whomwah.github.io/qlstephen/
    - quicklook-json           # http://www.sagtau.com/quicklookjson.html
    - skype                    # https://www.skype.com/
    - station                  # https://getstation.com/
    - tableplus                # https://tableplus.io/
    - transmit                 # https://panic.com/transmit/
    - tunnelbear               # https://www.tunnelbear.com/
    - vagrant                  # https://www.vagrantup.com/
    - webpquicklook            # https://github.com/dchest/webp-quicklook
    - wwdc                     # https://wwdc.io/

    # Fonts
    - font-fira-code

    #- android-sdk    # https://developer.android.com/index.html
    #- android-studio # https://developer.android.com/studio/index.html
    #- virtualbox     # https://www.virtualbox.org/

  # Comments are generated by:
  #
  #   $ for name in `pbpaste`; do echo "$name # $(brew info $name | sed -n '2p')"; done
  #
  packages:
    - bat                 # Clone of cat(1) with syntax highlighting and Git integration
    - binutils            # FSF Binutils for native development
    - carthage            # Decentralized dependency manager for Cocoa
    - clib                # Package manager for C programming
    - cloc                # Statistics utility to count lines of code
    - creasty/tools/rid   # Run commands in container as if were native
    - ctags               # Reimplementation of ctags(1)
    - direnv              # Load/unload environment variables based on $PWD
    - dtan4/tools/k8sec   # CLI tool to manage Kubernetes Secrets easily
    - envchain            # Secure your credentials in environment variables
    - eot-utils           # Tools to convert fonts from OTF/TTF to EOT format
    - exa                 # https://the.exa.website
    - expect              # Program that can automate interactive applications
    - fd                  # Simple, fast and user-friendly alternative to find
    - fontconfig          # XML-based font configuration API for X Windows
    - fontforge           # Command-line outline and bitmap font editor/converter
    - freetype            # Software library to render fonts
    - fswatch             # Monitor a directory for changes and run a shell command
    - gdb                 # GNU debugger
    - gdbm                # GNU database manager
    - gettext             # GNU internationalization (i18n) and localization (l10n) library
    - ghostscript         # Interpreter for PostScript and PDF
    - git                 # Distributed revision control system
    - git-lfs             # Git extension for versioning large files
    - gnupg               # GNU Pretty Good Privacy (PGP) package
    - heroku/brew/heroku  # Everything you need to get started with Heroku
    - imagemagick         # Tools and libraries to manipulate images in many formats
    - jbig2dec            # JBIG2 decoder and library (for monochrome documents)
    - jo                  # JSON output from a shell
    - jpeg                # Image manipulation library
    - jq                  # Lightweight and flexible command-line JSON processor
    - libepoxy            # Library for handling OpenGL function pointer management
    - libiconv            # Conversion library
    - libpcap             # Portable library for network traffic capture
    - libxml2             # GNOME XML library
    - libxslt             # C XSLT library for GNOME
    - massren             # Easily rename multiple files using your text editor
    - ngrep               # Network grep
    - nkf                 # Network Kanji code conversion Filter (NKF)
    - parallel            # GNU parallel shell command
    - pcre                # Perl compatible regular expressions library
    - protobuf            # Protocol buffers (Google's data interchange format)
    - python              # Interpreted, interactive, object-oriented programming language
    - screenresolution    # Get, set, and list display resolution
    - termtosvg           # Record terminal sessions as SVG animations
    - the_silver_searcher # Code-search similar to ack
    - tmux                # Terminal multiplexer
    - webp                # Image format providing lossless and lossy compression for web images
    - xctool              # Drop-in replacement for xcodebuild with a few extra features
    - yarn                # JavaScript package manager

mas:
  appstore_id:       '{{ appstore_id }}'
  appstore_password: '{{ appstore_password }}'

  # List installed apps by
  #
  #   $ mas list
  #
  applications:
    - '1031280567' # Postico
    - '1091189122' # Bear
    - '1333542190' # 1Password 7
    - '425424354'  # The Unarchiver
    - '497799835'  # Xcode
    - '540348655'  # Monosnap
    - '904280696'  # Things3
    - '928494006'  # PopHub
    - '975937182'  # Fantastical 2

launchagent:
  plist_dir: '{{ dotfiles_path }}/config/launchagent'

link:
  bash/bash_profile:         .bash_profile
  bash/bashrc:               .bashrc
  config/agignore:           .agignore
  config/alacritty.yml:      .config/alacritty/alacritty.yml
  config/ansible.cfg:        .ansible.cfg
  config/aws/config:         .aws/config
  config/cargo/config:       .cargo/config
  config/ctags:              .ctags
  config/curlrc:             .curlrc
  config/gitconfig:          .gitconfig
  config/gitignore:          .gitignore
  config/gocode/config.json: .config/gocode/config.json
  config/peco:               .peco
  config/pgclirc:            .pgclirc
  config/termtosvg:          .config/termtosvg
  ruby/bundle/config:        .bundle/config
  ruby/gemrc:                .gemrc
  ruby/irbrc:                .irbrc
  ruby/pryrc:                .pryrc
  ruby/railsrc:              .railsrc
  ruby/rbenv/default-gems:   .anyenv/envs/rbenv/default-gems
  ruby/rspec:                .rspec
  ruby/rubocop.yml:          .rubocop.yml
  tmux/tmux.conf:            .tmux.conf
  tmux:                      .tmux
  vim/gvimrc:                .gvimrc
  vim/vimrc:                 .vimrc
  vim:                       .vim
  zsh/zshenv:                .zshenv
  zsh/zshrc:                 .zshrc
  zsh:                       .zsh

anyenv:
  dir:         '{{ home_path }}/.anyenv'
  plugins_dir: '{{ home_path }}/.anyenv/plugins'
  envs_dir:    '{{ home_path }}/.anyenv/envs'

golang:
  packages:
    # tools
    - github.com/motemen/ghq        # Remote repository management made easy
    - github.com/peco/peco/cmd/peco # Simplistic interactive filtering tool
    - github.com/rakyll/hey         # HTTP load generator, ApacheBench (ab) replacement

    # dev tools
    - github.com/rogpeppe/godef            # find symbol information in Go source
    - github.com/sourcegraph/go-langserver # Go language server to add Go support to editors and other tools that use the Language Server Protocol (LSP)
    - golang.org/x/lint/golint             # Golint is a linter for Go source code
    - golang.org/x/tools/cmd/gopls         # LSP server for Go

nodejs:
  versions:
    - '10.15.3'

  packages:
    - eslint                        # https://github.com/eslint/eslint
    - tslint                        # https://github.com/palantir/tslint
    - typescript                    # https://github.com/Microsoft/TypeScript
    - typescript-language-server    # https://github.com/theia-ide/typescript-language-server
    - typescript-styled-plugin      # https://github.com/Microsoft/typescript-styled-plugin
    - vscode-css-languageserver-bin # https://github.com/vscode-langservers/vscode-css-languageserver-bin

ruby:
  versions:
    - '2.5.1'

  plugins_dir: '{{ anyenv.envs_dir }}/rbenv/plugins'

  plugins:
    - ianheggie/rbenv-binstubs # A Bundler binstubs Plugin for rbenv
    - rbenv/rbenv-default-gems # Automatically install gems every time you install a new version of Ruby

rust:
  components:
    - clippy        # https://github.com/rust-lang/rust-clippy
    - rls           # https://github.com/rust-lang/rls
    - rust-analysis # https://github.com/rust-lang/rls
    - rust-src      # https://github.com/rust-lang/rust

vagrant:
  boxes: {}

  plugins:
    - dotenv        # https://github.com/johnbellone/vagrant-dotenv ?
    - sahara        # https://github.com/jedi4ever/sahara
    - vagrant-share # https://www.vagrantup.com/docs/share/

vscode:
  link:
    vscode/keybindings.json: keybindings.json
    vscode/settings.json: settings.json
    vscode/snippets: snippets

  # code --list-extensions | sed -e 's/^/- /g' | pbcopy
  extensions:
    - alefragnani.Bookmarks
    - apollographql.vscode-apollo
    - christian-kohler.npm-intellisense
    - christian-kohler.path-intellisense
    - creasty.vscode-altr
    - creasty.vscode-candle-theme
    - cssho.vscode-svgviewer
    - dbaeumer.vscode-eslint
    - dsznajder.es7-react-js-snippets
    - eamodio.gitlens
    - eg2.vscode-npm-script
    - Equinusocio.vsc-material-theme
    - esbenp.prettier-vscode
    - fallenwood.vimL
    - formulahendry.auto-close-tag
    - formulahendry.auto-rename-tag
    - formulahendry.code-runner
    - geddski.macros
    - iocave.customize-ui
    - iocave.monkey-patch
    - ipatalas.vscode-postfix-ts
    - JerryHong.autofilename
    - jock.svg
    - jpoissonnier.vscode-styled-components
    - jtanx.ctagsx
    - karunamurti.haml
    - KnisterPeter.vscode-github
    - lannonbr.vscode-js-annotations
    - marchrock.vscode-ghq
    - mikestead.dotenv
    - ms-vscode.Go
    - ms-vscode.vscode-typescript-tslint-plugin
    - ms-vsliveshare.vsliveshare
    - msjsdiag.debugger-for-chrome
    - pflannery.vscode-versionlens
    - pnp.polacode
    - rebornix.ruby
    - shanehofstetter.rails-i18n
    - shinichi-takii.sql-bigquery
    - shinnn.stylelint
    - sleistner.vscode-fileutils
    - steoates.autoimport
    - streetsidesoftware.code-spell-checker
    - swindh.enumerator
    - Tyriar.sort-lines
    - vincaslt.highlight-matching-tag
    - vscodevim.vim
    - wayou.vscode-todo-highlight
    - wix.vscode-import-cost
    - wmaurer.change-case
    - wwm.better-align
    - xabikos.JavaScriptSnippets
    - yokoe.vscode-postfix-go
    - yzhang.markdown-all-in-one
    - zxh404.vscode-proto3
