- name:       Creasty's development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    is_ci:         '{{ lookup("env", "CI") | bool }}'

  environment:
    PATH: '/usr/local/bin:{{ anyenv.envs_dir }}/rbenv/shims:{{ anyenv.envs_dir }}/ndenv/shims:{{ anyenv.envs_dir }}/luaenv/shims:{{ anyenv.envs_dir }}/pyenv/shims:{{ anyenv.envs_dir }}/goenv/shims:{{ lookup("env", "PATH") }}'

  roles:
    #  preinstall
    #-----------------------------------------------
    - role: anyenv
      tags: ['install', 'anyenv']

    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']
    - role: ssh
      tags: ['basic', 'ssh']
    - role: zsh
      tags: ['basic', 'zsh']

    #  install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'homebrew']
    - role: whalebrew
      tags: ['install', 'whalebrew']
    - role: mas
      tags: ['install', 'mas']

    #  lang
    #-----------------------------------------------
    - role: ruby
      tags: ['lang', 'ruby']
    - role: nodejs
      tags: ['lang', 'nodejs']
    - role: lua
      tags: ['lang', 'lua']
    - role: python
      tags: ['lang', 'python']
    - role: golang
      tags: ['lang', 'golang']
    - role: swift
      tags: ['lang', 'swift']
    # - role: haskell
    #   tags: ['lang', 'haskell']
    # - role: rlang
    #   tags: ['lang', 'rlang']
    # - role: java
    #   tags: ['lang', 'java']
    # - role: erlang
    #   tags: ['lang', 'erlang']
    # - role: elixir
    #   tags: ['lang', 'elixir']
    # - role: scala
    #   tags: ['lang', 'scala']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'vim']
    - role: vagrant
      tags: ['app', 'vagrant']
    # - role: tex
    #   tags: ['app', 'tex']

    #  system
    #-----------------------------------------------
    - role: launchagent
      tags: ['system', 'launchagent']
    - role: osx
      tags: ['system', 'osx']
