- name:       Creasty's development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ home_path }}/dotfiles'
    brew_bin_path: '/usr/local/bin'

  roles:
    #  basic
    #-----------------------------------------------
    - role: anyenv
      tags: ['basic', 'basic.anyenv']
    - role: link
      tags: ['basic', 'basic.link']
    - role: ssh
      tags: ['basic', 'basic.ssh']

    #  install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'install.homebrew']
    - role: mas
      tags: ['install', 'install.mas']

    #  lang
    #-----------------------------------------------
    - role: ruby
      tags: ['lang', 'lang.ruby']
    - role: nodejs
      tags: ['lang', 'lang.nodejs']
    - role: golang
      tags: ['lang', 'lang.golang']
    - role: rust
      tags: ['lang', 'lang.rust']
    - role: java
      tags: ['lang', 'lang.java']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'app.vim']
    #- role: vagrant
    #  tags: ['app', 'app.vagrant']
    - role: vscode
      tags: ['app', 'app.vscode']

    #  system
    #-----------------------------------------------
    - role: launchagent
      tags: ['system', 'system.launchagent']
    - role: osx
      tags: ['system', 'system.osx']
    - role: zsh
      tags: ['system', 'system.zsh']
