- name:       Creasty's development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ lookup("env", "HOME") }}/dotfiles'

  roles:
    #  basic
    #-----------------------------------------------
    - role: link
      tags: ['basic', 'link']
    - role: shell
      tags: ['basic', 'shell']

    #  install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'homebrew']
    - role: mas
      tags: ['install', 'mas']
    - role: anyenv
      tags: ['install', 'anyenv']

    #  lang
    #-----------------------------------------------
    - role: ruby
      tags: ['lang', 'ruby']
    - role: nodejs
      tags: ['lang', 'nodejs']
    - role: r
      tags: ['lang', 'r']
    - role: haskell
      tags: ['lang', 'haskell']
    - role: lua
      tags: ['lang', 'lua']
    - role: python
      tags: ['lang', 'python']
    - role: golang
      tags: ['lang', 'golang']
    - role: java
      tags: ['lang', 'java']

    #  app
    #-----------------------------------------------
    - role: redis
      tags: ['app', 'redis']
    - role: vim
      tags: ['app', 'vim']
    - role: tex
      tags: ['app', 'tex']
    - role: vagrant
      tags: ['app', 'vagrant']
    - role: karabiner
      tags: ['app', 'karabiner']
    - role: automator
      tags: ['app', 'automator']

    #  system
    #-----------------------------------------------
    - role: launch_agent
      tags: ['system', 'launch_agent']
    - role: osx
      tags: ['system', 'osx']

    #  other
    #-----------------------------------------------
    - role: fonts
      tags: ['other', 'fonts']
    - role: envchain
      tags: ['other', 'envchain']
