- name:       Creasty's development environment
  hosts:      127.0.0.1
  connection: local

  roles:
    #  base
    #-----------------------------------------------
    - role: link
      tags: ['base', 'base.link']
    - role: ssh
      tags: ['base', 'base.ssh']

    #  install
    #-----------------------------------------------
    - role: homebrew
      tags: ['install', 'install.homebrew']

    #  lang
    #-----------------------------------------------
    - role: mise
      tags: ['lang', 'lang.mise', 'lang.mise.mise']
    - role: ruby
      tags: ['lang', 'lang.mise', 'lang.mise.ruby']
    - role: nodejs
      tags: ['lang', 'lang.mise', 'lang.mise.nodejs']
    - role: java
      tags: ['lang', 'lang.mise', 'lang.mise.java']
    - role: golang
      tags: ['lang', 'lang.golang']
    - role: rust
      tags: ['lang', 'lang.rust']
    - role: swift
      tags: ['lang', 'lang.swift']

    #  app
    #-----------------------------------------------
    - role: vim
      tags: ['app', 'app.vim']
    - role: vscode
      tags: ['app', 'app.vscode']
    - role: flutter
      tags: ['app', 'app.flutter']
    #- role: vagrant
    #  tags: ['app', 'app.vagrant']

    #  system
    #-----------------------------------------------
    - role: launchagent
      tags: ['system', 'system.launchagent']
    - role: osx
      tags: ['system', 'system.osx']
    - role: zsh
      tags: ['system', 'system.zsh']
