- name:       Creasty's development environment
  hosts:      127.0.0.1
  connection: local

  vars:
    home_path:     '{{ lookup("env", "HOME") }}'
    dotfiles_path: '{{ lookup("env", "HOME") }}/dotfiles'

  roles:
    - roles/sample
    - roles/link
