- set_fact:
    font: {}

- name: create directory
  file:
    dest:  '{{ home_path }}/Library/Fonts'
    state: directory

- name: copy fonts
  copy:
    src:  '{{ item }}'
    dest: '{{ home_path }}/Library/Fonts/'
  with_fileglob: '{{ font.glob }}'
  when: font.glob
