export DOTFILES_PATH="$HOME/dotfiles"

for file in $DOTFILES_PATH/zsh/{exports,aliases,functions,prompt}.zsh; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

if [ -d $HOME/.anyenv ]; then
  eval "$(anyenv init -)"
fi
