export DOTFILES_PATH="$HOME/dotfiles"

for file in $DOTFILES_PATH/zsh/{exports,aliases,functions,prompt,secrets}.zsh; do
  [ -r "$file" ] && [ -f "$file" ] && source "$file"
done
unset file

eval "$(rbenv init -)"
[ -d "$NVM_DIR" ] && source "$NVM_DIR/nvm.sh"
