- set_fact:
    rlang: {}

- name: install xquartz
  homebrew_cask:
    name:  xquartz
    state: present

- name: install r
  homebrew:
    name:  r
    state: present

- name: create tmp file
  command: mktemp
  register: mktemp

- block:
    - name: create package installer
      template:
        src:  'installer.r'
        dest: '{{ mktemp.stdout }}'
      when: rlang.packages

    - name: install packages
      command: |
        r --file '{{ mktemp.stdout }}'
      ignore_errors: yes
      when: rlang.packages

  always:
    - name: delete tmp file
      file:
        dest:  '{{ mktemp.stdout }}'
        state: absent
