nmap gcc <Leader>c<Space>
vmap gcc <Leader>cm
nmap gcs <Leader>cs
vmap gcs <Leader>cs
nmap gcy <Leader>cy
vmap gcy <Leader>cy
nmap gcI <Leader>c$
vmap gcI <Leader>c$
nmap gcA <Leader>cA
vmap gcA <Leader>cA
