export DOTFILES_PATH="$HOME/dotfiles"

export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/heroku/bin:$PATH
export PATH=$PATH:$HOME/.rbenv/shims
export PATH=$PATH:$HOME/.npm/node_modules/bin
export PATH=$PATH:/opt/local/bin

eval "$(rbenv init -)"

export NVM_DIR=$HOME/.nvm
[ -d "$NVM_DIR" ] && . "$NVM_DIR/nvm.sh"
