- name: create tmp file
  command: mktemp
  register: mktemp

- block:
    - name: create package installer
      template:
        src:  'installer.r'
        dest: '{{ mktemp.stdout }}'
      when: r_lang.packages

    - name: install packages
      command: |
        r --file '{{ mktemp.stdout }}'
      ignore_errors: yes
      when: r_lang.packages

  always:
    - name: delete tmp file
      file:
        dest:  '{{ mktemp.stdout }}'
        state: absent
