name: provisioning

on: [push]

jobs:
  provisioning:
    runs-on: macos-12 # https://github.com/actions/virtual-environments
    env:
      HOMEBREW_VERBOSE: 1
      DOTFILES_NOEDIT_SECRETS: 1
      ANSIBLE_DEBUG: 1
    strategy:
      fail-fast: false
      matrix:
        include:
          #- tags: base,install.homebrew.formula
          #- tags: base,lang
          - tags: install,app,system
            skip_tags: install.mas,install.homebrew.formula
    steps:
      - uses: actions/checkout@v2

      - name: Link to home
        run: |
          ln -sf "$PWD" "$HOME/dotfiles"

      - name: Clean slate
        run: |
          brew list | xargs brew uninstall --force --ignore-dependencies
          brew list --cask | xargs brew uninstall --force

      - name: Install SSH key
        run: |
          base64 -D <<< "$ID_RSA_FILE_B64" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        env:
          ID_RSA_FILE_B64: ${{ secrets.ID_RSA_FILE_B64 }}

      - name: Run
        run: ./up -vvvv --tags=${{ matrix.tags }} --skip-tags=${{ matrix.skip_tags }}
