name: provisioning

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  provisioning:
    runs-on: macos-latest
    env:
      HOMEBREW_VERBOSE: 1
      DOTFILES_NOEDIT_SECRETS: 1
    strategy:
      fail-fast: false
      matrix:
        opts:
          - --tags=base,install.homebrew.formula
          - --tags=base,lang
          - --tags=install,app,system --skip-tags=install.homebrew.formula
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Debug
        run: |
          cat provisioning/roles/nodejs/tasks/main.yml

      - name: Clean slate
        run: |
          brew list | xargs brew uninstall --force --ignore-dependencies
          brew list --cask | xargs brew uninstall --force

      - name: Install SSH key
        run: |
          base64 -D <<< "$ID_RSA_FILE_B64" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        env:
          ID_RSA_FILE_B64: ${{ secrets.ID_RSA_FILE_B64 }}

      - name: Run
        run: ./up -vvvv ${{ matrix.opts }}
