name: provisioning

on: [push]

jobs:
  provisioning:
    runs-on: macos-latest
    env:
      HOMEBREW_VERBOSE: 1
      DOTFILES_NOEDIT_SECRETS: 1
    strategy:
      matrix:
        opts:
          - --tags=base,install.homebrew.formula
          - --tags=base,lang
          - --tags=install,app,system --skip-tags=install.homebrew.formula
    steps:
      - uses: actions/checkout@v2
      - name: Clean slate
        run: |
          brew list | xargs brew uninstall --force --ignore-dependencies
          brew list --cask | xargs brew uninstall --force
      - name: Run
        run: ./up -vvvv ${{ matrix.opts }}
