- set_fact:
    scala: {}

- name: check scalaenv
  command: |
    which scalaenv
  register: which_scalaenv
  ignore_errors: yes

- name: install scalaenv
  command: |
    anyenv install scalaenv
  when: which_scalaenv.rc > 0

- name: get installed scala versions
  command: |
    scalaenv versions
  register: installed_versions

- name: install scala
  command: |
    scalaenv install '{{ item }}'
  when: |
    scala.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ scala.versions }}'

- name: set global scala
  command: |
    scalaenv global '{{ scala.versions[0] }}'
  when: scala.versions

#  sbt
#-----------------------------------------------
- name: check sbtenv
  command: |
    which sbtenv
  register: which_sbtenv
  ignore_errors: yes

- name: install sbtenv
  command: |
    anyenv install sbtenv
  when: which_sbtenv.rc > 0

- name: get installed sbt versions
  command: |
    sbtenv versions
  register: installed_sbt_versions

- name: install sbt
  command: |
    sbtenv install '{{ item }}'
  when: |
    scala.sbt_versions and installed_sbt_versions.stdout.find(item) == -1
  with_items: '{{ scala.sbt_versions }}'

- name: set global sbt
  command: |
    sbtenv global '{{ scala.sbt_versions[0] }}'
  when: scala.sbt_versions
